/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhom3.qlcf.view.form.hanghoa;

import com.nhom3.qlcf.dao.HangHoaDAO;
import com.nhom3.qlcf.helper.XuLy;
import com.nhom3.qlcf.model.HangHoa;
import com.nhom3.qlcf.view.form.login.FormLogin;
import static com.nhom3.qlcf.view.form.menu.FormMenu.jfMain;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author baotri1998
 */
public class KiemTraTonKho extends javax.swing.JPanel {

    /**
     * Creates new form KiemTraTonKho
     */
    public KiemTraTonKho() {
        initComponents();
        txtSearch.setText("Nhập tên hàng hóa");
        txtSearch.setForeground(Color.GRAY);
        XuLy.placeHolder(txtSearch, "Nhập tên hàng hóa");

        tblKhoHang.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
        tblKhoHang.setFont(new Font("Tohoma", Font.PLAIN, 12));
        tblKhoHang.getTableHeader().setOpaque(false);
        tblKhoHang.getTableHeader().setBackground(new Color(0, 0, 0));
        tblKhoHang.getTableHeader().setForeground(new Color(255, 255, 255));
        tblKhoHang.setRowHeight(25);

        tblKhoHang.removeColumn(tblKhoHang.getColumnModel().getColumn(5));
    }

    private void fillToTable(String tenHH) {
        List<HangHoa> list;
        if (tenHH.isEmpty() || tenHH.equals("Nhập tên hàng hóa")) {
            list = new HangHoaDAO().selectAll();
        } else {
            list = new HangHoaDAO().select("SELECT * FROM  dbo.HangHoa where tenHangHoa like '%" + tenHH + "%'");
        }
        DefaultTableModel table = (DefaultTableModel) tblKhoHang.getModel();

        table.setRowCount(0);
        list.stream().map((hangHoa) -> new Object[]{hangHoa.getTenHangHoa(), hangHoa.getDonViTinh(), hangHoa.getSoLuong(), hangHoa.getGiaVon(), hangHoa.getMoTa(), hangHoa.getMaHangHoa()}).forEachOrdered((row) -> {
            table.addRow(row);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnNenTimKiem = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        lblSearch = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jpnNenTable = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKhoHang = new javax.swing.JTable();
        jpnButton_xemTable1 = new javax.swing.JPanel();
        lblKiemKe = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnNenTimKiem.setBackground(new java.awt.Color(51, 51, 255));
        jpnNenTimKiem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jpnNenTimKiem.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 143, 29));

        lblSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(255, 255, 255));
        lblSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSearch.setText("Tìm Kiếm");
        lblSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSearchMousePressed(evt);
            }
        });
        jpnNenTimKiem.add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 0, 69, 29));

        add(jpnNenTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Giá Trị Kho Hàng");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 576, -1));

        jpnNenTable.setLayout(new java.awt.CardLayout());

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tblKhoHang.setForeground(new java.awt.Color(51, 51, 51));
        tblKhoHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Tên Mặt Hàng", "Đơn vị tính", "Số Lượng Tồn", "Giá Vốn", "Mô tả", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhoHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblKhoHang.setFocusable(false);
        tblKhoHang.setGridColor(new java.awt.Color(0, 0, 0));
        tblKhoHang.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblKhoHang.setRowHeight(25);
        tblKhoHang.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblKhoHang.setShowHorizontalLines(false);
        tblKhoHang.setShowVerticalLines(false);
        tblKhoHang.setSurrendersFocusOnKeystroke(true);
        tblKhoHang.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblKhoHang);
        if (tblKhoHang.getColumnModel().getColumnCount() > 0) {
            tblKhoHang.getColumnModel().getColumn(0).setResizable(false);
            tblKhoHang.getColumnModel().getColumn(1).setResizable(false);
            tblKhoHang.getColumnModel().getColumn(2).setResizable(false);
            tblKhoHang.getColumnModel().getColumn(3).setResizable(false);
            tblKhoHang.getColumnModel().getColumn(4).setResizable(false);
            tblKhoHang.getColumnModel().getColumn(5).setResizable(false);
        }

        jpnNenTable.add(jScrollPane2, "card2");

        add(jpnNenTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 89, 1036, 529));

        jpnButton_xemTable1.setBackground(new java.awt.Color(255, 255, 255));
        jpnButton_xemTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        lblKiemKe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblKiemKe.setForeground(new java.awt.Color(0, 0, 255));
        lblKiemKe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKiemKe.setText("Kiểm Kê Cuối Ngày");
        lblKiemKe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblKiemKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblKiemKeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblKiemKeMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jpnButton_xemTable1Layout = new javax.swing.GroupLayout(jpnButton_xemTable1);
        jpnButton_xemTable1.setLayout(jpnButton_xemTable1Layout);
        jpnButton_xemTable1Layout.setHorizontalGroup(
            jpnButton_xemTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnButton_xemTable1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblKiemKe, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnButton_xemTable1Layout.setVerticalGroup(
            jpnButton_xemTable1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnButton_xemTable1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblKiemKe, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        add(jpnButton_xemTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void lblKiemKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKiemKeMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblKiemKeMousePressed

    private void lblKiemKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblKiemKeMouseClicked
        // TODO add your handling code here:
        hide();
        FormKiemTraHangHoa.kiemtrahanghoa.jpnNen.hide();
        FormKiemTraHangHoa.kiemtrahanghoa.jpnNenKiemKe.show();

    }//GEN-LAST:event_lblKiemKeMouseClicked

    private void lblSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMousePressed
        // TODO add your handling code here:
        String tenHH = txtSearch.getText().trim();
        fillToTable(tenHH);
    }//GEN-LAST:event_lblSearchMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpnButton_xemTable1;
    private javax.swing.JPanel jpnNenTable;
    private javax.swing.JPanel jpnNenTimKiem;
    private javax.swing.JLabel lblKiemKe;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JTable tblKhoHang;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
