/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhom3.qlcf.view.form.hanghoa;

import com.nhom3.qlcf.dao.HangHoaDAO;
import com.nhom3.qlcf.helper.XuLy;
import com.nhom3.qlcf.model.HangHoa;
import java.util.List;

/**
 *
 * @author baotri1998
 */
public class ThemHang extends javax.swing.JPanel {

    public static ThemHang themHang;

    /**
     * Creates new form SuaHangHoa
     */
    public ThemHang() {
        initComponents();
        themHang = this;
    }

    private String getMaHH() {
        String maMoi;
        List<HangHoa> list = new HangHoaDAO().selectAll();
        if (list.isEmpty()) {
            maMoi = "HH001";
        } else {
            String maCuoi = list.get(list.size() - 1).getMaHangHoa();
            String soCuoi = maCuoi.replaceAll("\\D+", "").trim();
            int soMoi = Integer.parseInt(soCuoi) + 1;
            switch (String.valueOf(soMoi).length()) {
                case 1:
                    maMoi = "HH00" + soMoi;
                    break;
                case 2:
                    maMoi = "HH0" + soMoi;
                    break;
                default:
                    maMoi = "HH" + soMoi;
            }
        }
        return maMoi;

    }

    private boolean checkNull() {
        if (txtTenHang.getText().trim().isEmpty()) {
            lblThongBao.setText("Không được để trống tên hàng!!");
            return false;
        } else if (txtDVT.getText().trim().isEmpty()) {
            lblThongBao.setText("Không được để trống đơn vị tính");
            return false;
        } else if (txtGiaMoi.getText().trim().isEmpty()) {
            lblThongBao.setText("Không được để trống giá hàng hóa!!");
            return false;
        } else {
        }
        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTenHang = new javax.swing.JTextField();
        lblvien = new javax.swing.JLabel();
        lbluser = new javax.swing.JLabel();
        txtGiaMoi = new javax.swing.JTextField();
        lblpass2 = new javax.swing.JLabel();
        lblvien3 = new javax.swing.JLabel();
        lblpass3 = new javax.swing.JLabel();
        lblReset = new javax.swing.JLabel();
        lblThemHang = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        txtDVT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblThongBao = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN CẦN NHẬP");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setMaximumSize(new java.awt.Dimension(122, 17));
        jLabel1.setMinimumSize(new java.awt.Dimension(122, 17));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(122, 17));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 58));

        txtTenHang.setBorder(null);
        txtTenHang.setOpaque(false);
        txtTenHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenHangActionPerformed(evt);
            }
        });
        jPanel1.add(txtTenHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 259, 40));

        lblvien.setText("___________________________________________");
        jPanel1.add(lblvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 260, 30));

        lbluser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbluser.setText("Tên Hàng:");
        jPanel1.add(lbluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 80, 20));

        txtGiaMoi.setBorder(null);
        txtGiaMoi.setOpaque(false);
        jPanel1.add(txtGiaMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 259, 30));

        lblpass2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblpass2.setText("Đơn Vị Tính:");
        jPanel1.add(lblpass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 80, 20));

        lblvien3.setText("___________________________________________");
        jPanel1.add(lblvien3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 260, 30));

        lblpass3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblpass3.setText("Giá Nhập:");
        jPanel1.add(lblpass3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 100, 20));

        lblReset.setBackground(new java.awt.Color(255, 255, 255));
        lblReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblReset.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReset.setText("Reset");
        lblReset.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblReset.setOpaque(true);
        jPanel1.add(lblReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 110, 40));

        lblThemHang.setBackground(new java.awt.Color(255, 255, 255));
        lblThemHang.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblThemHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThemHang.setText("Thêm Hàng");
        lblThemHang.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblThemHang.setOpaque(true);
        lblThemHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblThemHangMousePressed(evt);
            }
        });
        jPanel1.add(lblThemHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 110, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Ghi chú:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane1.setViewportView(txtGhiChu);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 260, 60));

        txtDVT.setBorder(null);
        txtDVT.setOpaque(false);
        jPanel1.add(txtDVT, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 260, 40));

        jLabel2.setText("___________________________________________");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 260, 30));

        lblThongBao.setForeground(new java.awt.Color(255, 0, 0));
        lblThongBao.setText(" ");
        jPanel1.add(lblThongBao, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 260, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenHangActionPerformed

    private void lblThemHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemHangMousePressed
        // TODO add your handling code here:
        if (checkNull()) {
            try {
                HangHoa hangHoa = new HangHoa();
                hangHoa.setMaHangHoa(getMaHH());
                System.out.println("maHH " + getMaHH());
                hangHoa.setTenHangHoa(XuLy.xuLyTen(txtTenHang.getText()));
                hangHoa.setDonViTinh(XuLy.xuLyTen(txtDVT.getText()));
                hangHoa.setGiaVon(Double.parseDouble(txtGiaMoi.getText().trim()));
                hangHoa.setSoLuong(0);
                hangHoa.setMoTa(txtGhiChu.getText());
                boolean result = new HangHoaDAO().insert(hangHoa);
                if (result) {
                    lblThongBao.setText("Thêm hàng hóa mới thành công!!");
                } else {
                    lblThongBao.setText("Thêm hàng hóa mới thất bại!!");
                }
            } catch (NumberFormatException e) {
                lblThongBao.setText("Giá chỉ nhập kiểu số!!");
            }
        }

    }//GEN-LAST:event_lblThemHangMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblReset;
    private javax.swing.JLabel lblThemHang;
    private javax.swing.JLabel lblThongBao;
    private javax.swing.JLabel lblpass2;
    private javax.swing.JLabel lblpass3;
    private javax.swing.JLabel lbluser;
    private javax.swing.JLabel lblvien;
    private javax.swing.JLabel lblvien3;
    private javax.swing.JTextField txtDVT;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtGiaMoi;
    private javax.swing.JTextField txtTenHang;
    // End of variables declaration//GEN-END:variables
}
