/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhom3.qlcf.view.form.users;

import com.nhom3.qlcf.dao.NguoiDungDAO;
import com.nhom3.qlcf.helper.XuLy;
import com.nhom3.qlcf.model.NguoiDung;
import java.awt.Color;

/**
 *
 * @author baotri1998
 */
public class ChinhSuaTaiKhoan extends javax.swing.JPanel {

    /**
     * Creates new form Quanlyusers
     */
    NguoiDung ndung = null;

    public ChinhSuaTaiKhoan() {
        initComponents();
    }

    public boolean check() {
        String emails = "[\\w\\.]+@[\\w+]+\\.+[\\.\\w+]+";
        if (txtTimKiem.getText().trim().equals("Tìm Mã Nhân Viên") || txtTimKiem.getText().trim().equals("")) {
            lblthongbao.setText("Nhập Mã NV là bắt buột");
            lblthongbao.setForeground(Color.red);
            return false;
        } else {
            if (txtten.getText().trim().equals("")) {
                lblthongbao.setText("Tên không được bỏ trống");
                lblthongbao.setForeground(Color.red);
                return false;
            } else if (txtSDT.getText().trim().equals("")) {
                lblthongbao.setText("SĐT không được bỏ trống");
                lblthongbao.setForeground(Color.red);
                return false;
            } else if (!txtSDT.getText().matches("[0-9]+")) {
                lblthongbao.setText("SĐT phải là số");
                lblthongbao.setForeground(Color.red);
                return false;
            } else if (txtSDT.getText().length() > 10 && txtSDT.getText().length() < 13) {
                lblthongbao.setText("SĐT phải từ [10-13] số");
                lblthongbao.setForeground(Color.red);
                return false;
            } else if (txtemail.getText().equals("")) {
                lblthongbao.setText("Email không được bỏ trống!");
                lblthongbao.setForeground(Color.red);
                return false;
            } else if (!txtemail.getText().matches(emails)) {
                lblthongbao.setText("Email phải đúng định dạng VD: abc@gmail.com!");
                lblthongbao.setForeground(Color.red);
                return false;
            }

        }
        return true;
    }

    public void update() {

        try {
            NguoiDung nd = new NguoiDung();
            nd.setMaNguoidung(lblNhapMa.getText());
            nd.setHoTen(txtten.getText());
            nd.setDienThoai(txtSDT.getText());
            nd.setVaiTro(cbxNhanVien.getSelectedItem().toString());
            nd.setMatKhau(ndung.getMatKhau());
            nd.setTaiKhoan(lblTenDangNhap.getText());
            nd.setEmail(txtemail.getText());
            nd.setTrangThai(true);
            NguoiDungDAO ndDAO = new NguoiDungDAO();
            ndDAO.update(nd);
            lblthongbao.setText("Cập Nhật Thành Công");

        } catch (Exception e) {
            System.out.println(e);

        }

    }

    public void timMaNguoiDung() {

        NguoiDungDAO ndDAO = new NguoiDungDAO();
        ndDAO.selectID(txtTimKiem.getText());
        ndung = ndDAO.selectID(txtTimKiem.getText());
        lblTenDangNhap.setText(ndung.getTaiKhoan());
        lblNhapMa.setText(ndung.getMaNguoidung());
        cbxNhanVien.setSelectedItem(ndung.getVaiTro());
        txtten.setText(ndung.getHoTen());
        txtSDT.setText(ndung.getDienThoai());
        txtemail.setText(ndung.getEmail());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNhapMa = new javax.swing.JLabel();
        lblTenDangNhap = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbxNhanVien = new javax.swing.JComboBox<>();
        lblpass3 = new javax.swing.JLabel();
        txtten = new javax.swing.JTextField();
        lblvien2 = new javax.swing.JLabel();
        lblpass1 = new javax.swing.JLabel();
        lblvien3 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        lblMaNhanVien1 = new javax.swing.JLabel();
        lblthongbao = new javax.swing.JLabel();
        lblpass2 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lblvien4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNhapMa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNhapMa.setText("...");
        jPanel1.add(lblNhapMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 220, 43));

        lblTenDangNhap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTenDangNhap.setText("...");
        jPanel1.add(lblTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 220, 43));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Vai Trò:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 74, 27));

        cbxNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff", "Administration" }));
        jPanel1.add(cbxNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 242, -1));

        lblpass3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblpass3.setText("Số ĐT :");
        jPanel1.add(lblpass3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 80, 20));

        txtten.setBorder(null);
        txtten.setOpaque(false);
        jPanel1.add(txtten, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 259, 40));

        lblvien2.setText("___________________________________________");
        jPanel1.add(lblvien2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 260, 30));

        lblpass1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblpass1.setText("Tên Nhân Viên:");
        jPanel1.add(lblpass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, 20));

        lblvien3.setText("___________________________________________");
        jPanel1.add(lblvien3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 260, 30));

        txtSDT.setBorder(null);
        txtSDT.setOpaque(false);
        jPanel1.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 259, 40));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Reset");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 110, 40));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Câp Nhật");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 110, 40));

        lblTen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTen.setText("Tên Đăng Nhập:");
        jPanel1.add(lblTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 43));

        lblMaNhanVien1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMaNhanVien1.setText("Mã Nhân Viên:");
        jPanel1.add(lblMaNhanVien1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 43));

        lblthongbao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblthongbao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblthongbao.setText(".");
        jPanel1.add(lblthongbao, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 10, 360, -1));

        lblpass2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblpass2.setText("Email:");
        jPanel1.add(lblpass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 70, 20));

        txtemail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtemail.setBorder(null);
        txtemail.setOpaque(false);
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 260, 40));

        lblvien4.setText("___________________________________________");
        jPanel1.add(lblvien4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 260, 30));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tìm Kiếm");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        txtTimKiem.setText("Tìm Mã Nhân Viên");
        txtTimKiem.setForeground(Color.gray);
        XuLy.placeHolder(txtTimKiem, "Tìm Mã Nhân Viên");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        NguoiDungDAO nd = new NguoiDungDAO();
        if (txtTimKiem.getText().trim().equals("Tìm Mã Nhân Viên") || txtTimKiem.getText().trim().equals("")) {
            lblthongbao.setText("Nhập Mã NV là bắt buột");
            lblthongbao.setForeground(Color.red);

        } else if (!nd.checkMa(txtTimKiem.getText())) {
            lblthongbao.setText("Nhập Mã NV không tồn tại!");
            lblthongbao.setForeground(Color.red);
        } else {
             lblthongbao.setText("");
            timMaNguoiDung();
        }

    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
        if (check()) {
            lblthongbao.setForeground(Color.GREEN);
            update();
        }

    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        jLabel1.setForeground(Color.WHITE);
        jPanel2.setBackground(Color.WHITE);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
         jLabel1.setForeground(Color.WHITE);
        jPanel2.setBackground(Color.BLACK);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
                jLabel7.setBackground(Color.BLACK);
         jLabel7.setForeground(Color.white);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
         jLabel6.setBackground(Color.BLACK);
         jLabel6.setForeground(Color.white);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
                jLabel7.setBackground(Color.white);
         jLabel7.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
         jLabel6.setBackground(Color.white);
         jLabel6.setForeground(Color.BLACK);
    }//GEN-LAST:event_jLabel6MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxNhanVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblMaNhanVien1;
    private javax.swing.JLabel lblNhapMa;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTenDangNhap;
    private javax.swing.JLabel lblpass1;
    private javax.swing.JLabel lblpass2;
    private javax.swing.JLabel lblpass3;
    private javax.swing.JLabel lblthongbao;
    private javax.swing.JLabel lblvien2;
    private javax.swing.JLabel lblvien3;
    private javax.swing.JLabel lblvien4;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtten;
    // End of variables declaration//GEN-END:variables
}
