/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhom3.qlcf.view.form.users;

import com.nhom3.qlcf.dao.NguoiDungDAO;
import com.nhom3.qlcf.helper.Loginhelper;
import com.nhom3.qlcf.helper.XuLy;
import com.nhom3.qlcf.model.NguoiDung;
import static com.nhom3.qlcf.view.form.users.FormTK.jpltable;
import static com.nhom3.qlcf.view.form.users.FormTK.lblTitle;
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;

/**
 *
 * @author baotri1998
 */
public class ThongTinTK extends javax.swing.JPanel {

    /**
     * Creates new form Quanlyusers
     */
    NguoiDung ndung = null;

    public ThongTinTK() {
        initComponents();
        new Loginhelper().getLogin(lblTenDangNhap);
        timMaNguoiDung();
    }

    public boolean check() {
        String emails = "[\\w\\.]+@[\\w+]+\\.+[\\.\\w+]+";

        if (txtten.getText().trim().equals("")) {
            lblthongbao.setText("Tên không được bỏ trống");
              txtten.setText(txtten.getName());
            lblthongbao.setForeground(Color.red);
            return false;
        } else if (txtSDT.getText().trim().equals("")) {
            lblthongbao.setText("SĐT không được bỏ trống");
            txtSDT.setText(txtSDT.getName());
            lblthongbao.setForeground(Color.red);
            return false;
        } else if (!txtSDT.getText().matches("[0-9]+")) {
            lblthongbao.setText("SĐT phải là số");
            lblthongbao.setForeground(Color.red);
            return false;
        } else if (txtSDT.getText().length() > 10 && txtSDT.getText().length() < 13) {
            lblthongbao.setText("SĐT phải từ [10-13] số");
            lblthongbao.setForeground(Color.red);
            return false;
        } else if (txtemail.getText().equals("")) {
            lblthongbao.setText("Email không được bỏ trống!");
               txtemail.setText(txtemail.getName());
            lblthongbao.setForeground(Color.red);
            return false;
        } else if (!txtemail.getText().matches(emails)) {
            lblthongbao.setText("Email phải đúng định dạng VD: abc@gmail.com!");
            lblthongbao.setForeground(Color.red);
            return false;

        }
        return true;
    }

    public void update() {

        try {
            NguoiDung nd = new NguoiDung();
            nd.setMaNguoidung(lblMa.getText());
            nd.setHoTen(txtten.getText());
            nd.setDienThoai(txtSDT.getText());
            nd.setVaiTro(lblvaitro.getText());
            nd.setMatKhau(ndung.getMatKhau());
            nd.setTaiKhoan(lblTenDangNhap.getText());
            nd.setEmail(txtemail.getText());
            nd.setTrangThai(true);
            NguoiDungDAO ndDAO = new NguoiDungDAO();
            ndDAO.update(nd);
            lblthongbao.setText("Cập Nhật Thành Công");

        } catch (Exception e) {
            System.out.println(e);

        }

    }

    public void timMaNguoiDung() {

        NguoiDungDAO ndDAO = new NguoiDungDAO();
        ndDAO.selectID(lblTenDangNhap.getName());
        ndung = ndDAO.selectID(lblTenDangNhap.getName());
        lblTenDangNhap.setText(ndung.getTaiKhoan());
        lblMa.setText(ndung.getMaNguoidung());
        lblvaitro.setText(ndung.getVaiTro());
        txtSDT.setName(ndung.getDienThoai());
        txtten.setText(ndung.getHoTen());
        txtten.setName(ndung.getHoTen());
        txtSDT.setText(ndung.getDienThoai());
        txtemail.setText(ndung.getEmail());
        txtemail.setName(ndung.getEmail());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMa = new javax.swing.JLabel();
        lblTenDangNhap = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblpass3 = new javax.swing.JLabel();
        txtten = new javax.swing.JTextField();
        lblvien2 = new javax.swing.JLabel();
        lblpass1 = new javax.swing.JLabel();
        lblvien3 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTen = new javax.swing.JLabel();
        lblMaNhanVien1 = new javax.swing.JLabel();
        lblthongbao = new javax.swing.JLabel();
        lblpass2 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        lblvien4 = new javax.swing.JLabel();
        lblvaitro = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMa.setText("...");
        jPanel1.add(lblMa, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 220, 43));

        lblTenDangNhap.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTenDangNhap.setText("...");
        jPanel1.add(lblTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 220, 43));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Vai Trò:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 74, 27));

        lblpass3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblpass3.setText("Số ĐT :");
        jPanel1.add(lblpass3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 80, 20));

        txtten.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtten.setBorder(null);
        txtten.setOpaque(false);
        jPanel1.add(txtten, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 259, 40));

        lblvien2.setText("___________________________________________");
        jPanel1.add(lblvien2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 260, 30));

        lblpass1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblpass1.setText("Tên Nhân Viên:");
        jPanel1.add(lblpass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, 20));

        lblvien3.setText("___________________________________________");
        jPanel1.add(lblvien3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 260, 30));

        txtSDT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSDT.setBorder(null);
        txtSDT.setOpaque(false);
        jPanel1.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 259, 40));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Đổi Mật Khẩu");
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 110, 40));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Cập Nhật");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 110, 40));

        lblTen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTen.setText("Tên Đăng Nhập:");
        jPanel1.add(lblTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 43));

        lblMaNhanVien1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMaNhanVien1.setText("Mã Nhân Viên:");
        jPanel1.add(lblMaNhanVien1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, 43));

        lblthongbao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblthongbao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblthongbao.setText(".");
        jPanel1.add(lblthongbao, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 10, 360, -1));

        lblpass2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblpass2.setText("Email:");
        jPanel1.add(lblpass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 70, 20));

        txtemail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtemail.setBorder(null);
        txtemail.setOpaque(false);
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 260, 40));

        lblvien4.setText("___________________________________________");
        jPanel1.add(lblvien4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 260, 30));

        lblvaitro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblvaitro.setText("...");
        jPanel1.add(lblvaitro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 220, 43));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        // TODO add your handling code here:
        if (check()) {
            lblthongbao.setForeground(Color.GREEN);
            update();
        }

    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        // TODO add your handling code here:
        lblTitle.setText("ĐỔI MẬT KHẨU");
        jpltable.removeAll();
        jpltable.updateUI();
        jpltable.add(new DoiMatKhau());
        jpltable.repaint();
        jpltable.updateUI();
    }//GEN-LAST:event_jLabel6MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    protected static javax.swing.JLabel lblMa;
    private javax.swing.JLabel lblMaNhanVien1;
    private javax.swing.JLabel lblTen;
    private javax.swing.JLabel lblTenDangNhap;
    private javax.swing.JLabel lblpass1;
    private javax.swing.JLabel lblpass2;
    private javax.swing.JLabel lblpass3;
    private javax.swing.JLabel lblthongbao;
    private javax.swing.JLabel lblvaitro;
    private javax.swing.JLabel lblvien2;
    private javax.swing.JLabel lblvien3;
    private javax.swing.JLabel lblvien4;
    private javax.swing.JTextField txtSDT;
    protected static javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtten;
    // End of variables declaration//GEN-END:variables
}
