/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhom3.qlcf.view.form.login;

import com.nhom3.qlcf.dao.NguoiDungDAO;
import com.nhom3.qlcf.view.form.users.*;
import com.nhom3.qlcf.dao.SanPhamDAO;
import com.nhom3.qlcf.helper.Designhelper;
import com.nhom3.qlcf.helper.Hashing;
import com.nhom3.qlcf.helper.JDBCHelper;
import com.nhom3.qlcf.helper.SendMailHelper;
import com.nhom3.qlcf.helper.Timehelper;
import com.nhom3.qlcf.helper.sendsmscode;
import static com.nhom3.qlcf.view.form.banhang.FormBanHang.list;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author baotri1998
 */
public class QuenMatKhau extends javax.swing.JDialog {

    String code;
    String code1;

    /**
     * Creates new form LayLaiMatKhau
     */
    public QuenMatKhau(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    public QuenMatKhau(java.awt.Frame parent, boolean modal, String email) {
        super(parent, modal);
        initComponents();
        txttofrom.setText(email);
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txttofrom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblthongbao = new javax.swing.JLabel();
        lbllayma = new javax.swing.JLabel();
        lblchapnhan = new javax.swing.JLabel();
        lbltat = new javax.swing.JLabel();
        txtcode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("SDT/email");

        txttofrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttofromActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Mã Code");

        lblthongbao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblthongbao.setForeground(new java.awt.Color(255, 0, 0));
        lblthongbao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblthongbao.setText(".");

        lbllayma.setBackground(new java.awt.Color(255, 255, 255));
        lbllayma.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbllayma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllayma.setText("Lấy Mã");
        lbllayma.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        lbllayma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbllayma.setOpaque(true);
        lbllayma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbllaymaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbllaymaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbllaymaMousePressed(evt);
            }
        });

        lblchapnhan.setBackground(new java.awt.Color(255, 255, 255));
        lblchapnhan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblchapnhan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblchapnhan.setText("Chấp Nhận");
        lblchapnhan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        lblchapnhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblchapnhan.setOpaque(true);
        lblchapnhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblchapnhanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblchapnhanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblchapnhanMousePressed(evt);
            }
        });

        lbltat.setBackground(new java.awt.Color(255, 255, 255));
        lbltat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbltat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltat.setText("Tắt");
        lbltat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        lbltat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbltat.setOpaque(true);
        lbltat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbltatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbltatMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbltatMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblthongbao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txttofrom, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtcode, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbllayma, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblchapnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(lbltat, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblthongbao)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txttofrom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtcode)
                            .addComponent(lbllayma, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .addGap(36, 36, 36)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblchapnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbltat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttofromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttofromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttofromActionPerformed

    private void lbllaymaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllaymaMousePressed
        // TODO add your handling code here:
        lblthongbao.setText("Mã đang gửi...");
        Timehelper timehelper = new Timehelper();
        timehelper.TimerLoad(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                try {
                    if (txttofrom.getText().trim().equals("")) {
                        lblthongbao.setText("Nhập SDT/email của bạn");
                    } else if (!new NguoiDungDAO().checkSDT(txttofrom.getText()) && txttofrom.getText().matches("[0-9]+")) {
                        lblthongbao.setText("SĐT không đúng hoặc chưa đăng ký!");
                    } else if (!new NguoiDungDAO().checkEmail(txttofrom.getText()) && !txttofrom.getText().matches("[0-9]+")) {
                        lblthongbao.setText("Email không đúng hoặc chưa đăng ký!");
                    } else {
                        if (!txttofrom.getText().trim().equals("") && !txttofrom.getText().matches("[0-9]+")) {
                            code = Hashing.randomCode(4);
                            SendMailHelper.sendMail(txttofrom.getText(), code);
                            lblthongbao.setText("Mã đã được gửi vào email của bạn");
                            lblthongbao.setForeground(Color.GREEN);
                        } else if (txttofrom.getText().matches("[0-9]+")) {
                            lblthongbao.setText("Mã đã được gửi đến SĐT của bạn");
                            code = Hashing.ramdomso(6);
                            new sendsmscode().sendSMScode(txttofrom.getText(), code);
                            lblthongbao.setForeground(Color.GREEN);
                        } else {
                            lblthongbao.setText("Nhập SDT/email của bạn");
                        }
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Lỗi");
                }

                timehelper.t.stop();
            }
        }
        );


    }//GEN-LAST:event_lbllaymaMousePressed
    public boolean check() {
        if (txttofrom.getText().trim().equals("")) {
            lblthongbao.setText("Không thể bỏ SDT/email của bạn");
            lblthongbao.setForeground(Color.red);
            return false;
        } else if (txtcode.getText().trim().equals("")) {
            lblthongbao.setText("Chưa nhập mã code!");
            lblthongbao.setForeground(Color.red);
            return false;
        } else if (!txtcode.getText().equals(code)) {
            lblthongbao.setText("Mã code không đúng!");
            lblthongbao.setForeground(Color.red);
            return false;
        }
        return true;
    }
    private void lblchapnhanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblchapnhanMousePressed
        // TODO add your handling code here:
        if (check()) {
            txttofrom.setName(txttofrom.getText());
            doiatkhau doi = new doiatkhau(null, rootPaneCheckingEnabled);
            doi.setVisible(rootPaneCheckingEnabled);
            lblthongbao.setText("Lấy lại mật khẩu thành công!");
            lblthongbao.setForeground(Color.GREEN);
            dispose();
        }

    }//GEN-LAST:event_lblchapnhanMousePressed

    private void lbltatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltatMousePressed
        // TODO add your handling code here:
        code = null;
        dispose();
    }//GEN-LAST:event_lbltatMousePressed

    private void lblchapnhanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblchapnhanMouseEntered
        // TODO add your handling code here:
        lblchapnhan.setBackground(Color.BLACK);
        lblchapnhan.setForeground(Color.WHITE);
    }//GEN-LAST:event_lblchapnhanMouseEntered

    private void lblchapnhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblchapnhanMouseExited
        // TODO add your handling code here:
        lblchapnhan.setBackground(Color.WHITE);
        lblchapnhan.setForeground(Color.BLACK);

    }//GEN-LAST:event_lblchapnhanMouseExited

    private void lbllaymaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllaymaMouseEntered
        // TODO add your handling code here:
        lbllayma.setBackground(Color.BLACK);
        lbllayma.setForeground(Color.WHITE);
    }//GEN-LAST:event_lbllaymaMouseEntered

    private void lbllaymaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllaymaMouseExited
        // TODO add your handling code here:
        lbllayma.setBackground(Color.WHITE);
        lbllayma.setForeground(Color.BLACK);
    }//GEN-LAST:event_lbllaymaMouseExited

    private void lbltatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltatMouseEntered
        // TODO add your handling code here:
        lbltat.setBackground(Color.BLACK);
        lbltat.setForeground(Color.WHITE);
    }//GEN-LAST:event_lbltatMouseEntered

    private void lbltatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltatMouseExited
        // TODO add your handling code here:
      lbltat.setBackground(Color.WHITE);
        lbltat.setForeground(Color.BLACK);
    }//GEN-LAST:event_lbltatMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuenMatKhau dialog = new QuenMatKhau(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblchapnhan;
    private javax.swing.JLabel lbllayma;
    private javax.swing.JLabel lbltat;
    private javax.swing.JLabel lblthongbao;
    private javax.swing.JTextField txtcode;
    protected static javax.swing.JTextField txttofrom;
    // End of variables declaration//GEN-END:variables
}
