/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhom3.qlcf.view.phieunhap;

import com.nhom3.qlcf.helper.JDBCHelper;
import com.nhom3.qlcf.model.CTPhieuNhap;
import com.nhom3.qlcf.model.HangHoa;
import com.nhom3.qlcf.model.NguoiDung;
import com.nhom3.qlcf.model.NhaCungCap;
import com.nhom3.qlcf.model.PhieuNhap;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author baotri1998
 */
public class chieuTietPhieu extends javax.swing.JDialog {

    public List<CTPhieuNhap> addCTList = null;
    String maphieu;

    /**
     * Creates new form chieuTietPhieu
     */
    public chieuTietPhieu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Show();
    }
    DefaultTableModel model = null;

    public chieuTietPhieu(java.awt.Frame parent, boolean modal, String maPhieu) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.maphieu = maPhieu;
        Show();
    }

    public void Addlist() {
        ResultSet rs = null;
        if (maphieu != null) {
            rs = JDBCHelper.executeQuery("EXEC proCTPhieuNhap @maphieu ='" + maphieu + "'");
        } else {
            rs = JDBCHelper.executeQuery("EXEC proshowCTPhieuNhap ");
        }
        try {
            addCTList = new ArrayList<>();
            while (rs.next()) {
                PhieuNhap phieu = new PhieuNhap();
                CTPhieuNhap ctp = new CTPhieuNhap();
                NguoiDung nd = new NguoiDung();
                HangHoa hh = new HangHoa();
                NhaCungCap ncc = new NhaCungCap();
                phieu.setMaPhieu(rs.getString(1));
                hh.setMaHangHoa(rs.getString(2));
                hh.setTenHangHoa(rs.getString(3));
                hh.setGiaVon(rs.getDouble(4));
                ncc.setTenNhaCC(rs.getString(5));
                ncc.setDiaChi(rs.getString(6));
                ctp.setSoLuong(rs.getInt(7));
                phieu.setNgayNhap(rs.getDate(9));
                phieu.setTongTien(rs.getDouble(8));
                nd.setMaNguoidung(rs.getString(10));
                phieu.setMaNguoiDung(nd);
                phieu.setMaNhaCungCap(ncc);
                ctp.setMaPhieuNhap(phieu);
                ctp.setMaHangHoa(hh);
                addCTList.add(ctp);

            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void Show() {
        try {
            Addlist();
            model = (DefaultTableModel) tblquanlyphieu.getModel();
            model.setRowCount(0);
            try {
                addCTList.stream().map((kh) -> new Object[]{
                    kh.getMaPhieuNhap().getMaPhieu(), kh.getMaHangHoa().getMaHangHoa(),
                    kh.getMaHangHoa().getTenHangHoa(), kh.getMaHangHoa().getGiaVon(),
                    kh.getMaPhieuNhap().getMaNhaCungCap().getTenNhaCC(), kh.getMaPhieuNhap().getMaNhaCungCap().getDiaChi(),
                    kh.getSoLuong(), kh.getMaPhieuNhap().getTongTien(), kh.getMaPhieuNhap().getNgayNhap(), kh.getMaPhieuNhap().getMaNguoiDung().getMaNguoidung()
                }).forEachOrdered((row) -> {
                    model.addRow(row);
                });
            } catch (Exception e) {
                System.out.println(e);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblquanlyphieu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tblquanlyphieu.setForeground(new java.awt.Color(51, 51, 51));
        tblquanlyphieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Phiếu", "Mã HH", "Tên Hàng", "Đơn Giá", "Tên Công Ty", "Địa Chỉ", "SL", "Tổng Tiền", "Ngày Nhập", "Mã NV"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblquanlyphieu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblquanlyphieu.setFocusable(false);
        tblquanlyphieu.setGridColor(new java.awt.Color(0, 0, 0));
        tblquanlyphieu.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblquanlyphieu.setRowHeight(25);
        tblquanlyphieu.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblquanlyphieu.setShowHorizontalLines(false);
        tblquanlyphieu.setShowVerticalLines(false);
        tblquanlyphieu.setSurrendersFocusOnKeystroke(true);
        tblquanlyphieu.getTableHeader().setReorderingAllowed(false);
        tblquanlyphieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblquanlyphieuMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblquanlyphieu);
        if (tblquanlyphieu.getColumnModel().getColumnCount() > 0) {
            tblquanlyphieu.getColumnModel().getColumn(0).setResizable(false);
            tblquanlyphieu.getColumnModel().getColumn(0).setPreferredWidth(40);
            tblquanlyphieu.getColumnModel().getColumn(1).setResizable(false);
            tblquanlyphieu.getColumnModel().getColumn(1).setPreferredWidth(40);
            tblquanlyphieu.getColumnModel().getColumn(2).setResizable(false);
            tblquanlyphieu.getColumnModel().getColumn(2).setPreferredWidth(120);
            tblquanlyphieu.getColumnModel().getColumn(3).setResizable(false);
            tblquanlyphieu.getColumnModel().getColumn(3).setPreferredWidth(60);
            tblquanlyphieu.getColumnModel().getColumn(4).setResizable(false);
            tblquanlyphieu.getColumnModel().getColumn(4).setPreferredWidth(100);
            tblquanlyphieu.getColumnModel().getColumn(5).setResizable(false);
            tblquanlyphieu.getColumnModel().getColumn(5).setPreferredWidth(150);
            tblquanlyphieu.getColumnModel().getColumn(6).setResizable(false);
            tblquanlyphieu.getColumnModel().getColumn(6).setPreferredWidth(35);
            tblquanlyphieu.getColumnModel().getColumn(7).setResizable(false);
            tblquanlyphieu.getColumnModel().getColumn(7).setPreferredWidth(60);
            tblquanlyphieu.getColumnModel().getColumn(8).setResizable(false);
            tblquanlyphieu.getColumnModel().getColumn(8).setPreferredWidth(65);
            tblquanlyphieu.getColumnModel().getColumn(9).setResizable(false);
            tblquanlyphieu.getColumnModel().getColumn(9).setPreferredWidth(40);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/excel.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Print:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblquanlyphieuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblquanlyphieuMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tblquanlyphieuMousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chieuTietPhieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chieuTietPhieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chieuTietPhieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chieuTietPhieu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                chieuTietPhieu dialog = new chieuTietPhieu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblquanlyphieu;
    // End of variables declaration//GEN-END:variables
}
