/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhom3.qlcf.view;


import com.nhom3.qlcf.view.form.login.FormLogin;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.BoxLayout;
import javax.swing.Timer;

/**
 *
 * @author baotri1998
 */
public class Run extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public static Run main;
    Timer t;
    public static String folderPAth = System.getenv("ProgramData") + "\\" + "QLCF\\";

    public Run() {
        initComponents();
        setLocationRelativeTo(null);
         try {
            setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/nhom3/qlcf/img/logoBar.png")));
        } catch (Exception e) {
        }
        /* jpnLogin.setBackground(new Color(0, 0, 0, 134));
        jpnNenButton_login.setBackground(new Color(0, 0, 0, 64));
        jfMain.hide();
        CardLayout.hide();*/
        getContentPane().setBackground(new Color(0, 0, 0, 0));
        setBackground(new Color(0, 0, 0, 0));
        ActionListener action = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int percent = proBar.getValue() + 1;
                proBar.setValue(percent);
                if (percent >= 100) {
                    lblLogo.hide();
                    proBar.hide();
                    lblimg.hide();
                    setLayout(new BoxLayout(getContentPane(), BoxLayout.LINE_AXIS));
                    add(new FormLogin());
                    t.stop();
                }
            }
        };
        t = new Timer(32, action);
        t.start();

        main = this;
        
        createImagesFolder("Images");
    }

    private void copyImagesFromResources(){
        
    }
    private void createImagesFolder(String folderName){
        
        File folder = new File(folderPAth + folderName);
        if (!folder.exists()) {
            folder.mkdirs();
            System.out.println("Folder has been created!");
        } else {
            System.out.println("Folder exist");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        proBar = new javax.swing.JProgressBar();
        lblimg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1100, 700));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/logoCafe2.gif"))); // NOI18N
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 400, -1));

        proBar.setBackground(new java.awt.Color(255, 255, 255));
        proBar.setForeground(new java.awt.Color(0, 102, 204));
        proBar.setStringPainted(true);
        getContentPane().add(proBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 520, 300, -1));

        lblimg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/logoCafe3.png"))); // NOI18N
        getContentPane().add(lblimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 390, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Run().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblimg;
    private javax.swing.JProgressBar proBar;
    // End of variables declaration//GEN-END:variables
}
