/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhom3.qlcf.view.form.sanpham;

import com.nhom3.qlcf.dao.LoaiSanPhamDAO;
import com.nhom3.qlcf.dao.SanPhamDAO;
import com.nhom3.qlcf.model.LoaiSanPham;
import com.nhom3.qlcf.model.SanPham;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.List;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author baotri1998
 */
public class DanhSachSP extends javax.swing.JDialog {

    public List<SanPham> listSanPham = null;
    String tenSanPham;

    /**
     * Creates new form chieuTietPhieu
     */
    public DanhSachSP(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        Show();
    }

    DefaultTableModel model = null;
    NumberFormat chuyentien = new DecimalFormat("#,###,###");

    public DanhSachSP(java.awt.Frame parent, boolean modal, String tenSanPham) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.tenSanPham = tenSanPham;
        Show();
    }

    public void Addlist() {
        if (tenSanPham.isEmpty() || tenSanPham.equals("Tên sản phẩm")) {
            listSanPham = new SanPhamDAO().selectAll();
        } else {
            listSanPham = new SanPhamDAO().select("Select * from dbo.SanPham where tenSp like N'%" + tenSanPham + "%'");
        }

    }

    public void Show() {

        Addlist();
        model = (DefaultTableModel) tblDanhSachSP.getModel();
        model.setRowCount(0);

        if (!listSanPham.isEmpty()) {
            listSanPham.forEach((sanPham) -> {
                String maLoaiSP = sanPham.getMaLoaiSanPham().getMaLoai();
                LoaiSanPham lSP = new LoaiSanPhamDAO().selectID(maLoaiSP);
                Object[] row = new Object[]{
                    sanPham.getTenSp(),
                    lSP.getTenLoai(),
                    new DecimalFormat("#,###,###").format(sanPham.getGiaBan()) + " vnđ",
                    sanPham.isTrangThai() ? "Còn bán" : "Ngừng bán",
                    sanPham.getHinhAnh()
                };
                model.addRow(row);
            }
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDanhSachSP = new javax.swing.JTable();
        lblCloseButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tblDanhSachSP.setForeground(new java.awt.Color(51, 51, 51));
        tblDanhSachSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên Sản Phẩm", "Loại Sản Phẩm", "Giá Bán", "Trạng Thái", "Hình ảnh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDanhSachSP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblDanhSachSP.setFocusable(false);
        tblDanhSachSP.setGridColor(new java.awt.Color(0, 0, 0));
        tblDanhSachSP.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblDanhSachSP.setRowHeight(25);
        tblDanhSachSP.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblDanhSachSP.setShowHorizontalLines(false);
        tblDanhSachSP.setShowVerticalLines(false);
        tblDanhSachSP.setSurrendersFocusOnKeystroke(true);
        tblDanhSachSP.getTableHeader().setReorderingAllowed(false);
        tblDanhSachSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblDanhSachSPMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblDanhSachSP);
        if (tblDanhSachSP.getColumnModel().getColumnCount() > 0) {
            tblDanhSachSP.getColumnModel().getColumn(0).setResizable(false);
            tblDanhSachSP.getColumnModel().getColumn(0).setPreferredWidth(120);
            tblDanhSachSP.getColumnModel().getColumn(1).setResizable(false);
            tblDanhSachSP.getColumnModel().getColumn(1).setPreferredWidth(60);
            tblDanhSachSP.getColumnModel().getColumn(2).setResizable(false);
            tblDanhSachSP.getColumnModel().getColumn(2).setPreferredWidth(100);
            tblDanhSachSP.getColumnModel().getColumn(3).setResizable(false);
            tblDanhSachSP.getColumnModel().getColumn(3).setPreferredWidth(50);
            tblDanhSachSP.getColumnModel().getColumn(4).setResizable(false);
            tblDanhSachSP.getColumnModel().getColumn(4).setPreferredWidth(135);
        }

        lblCloseButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCloseButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCloseButton.setText("X");
        lblCloseButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        lblCloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCloseButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseButtonMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 866, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDanhSachSPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachSPMousePressed
        // TODO add your handling code here:
        int index = tblDanhSachSP.getSelectedRow();
        SuaSP.sanPham = listSanPham.get(index);

        FormSuaXoaSP_admin.jplnen.removeAll();
        FormSuaXoaSP_admin.jplnen.updateUI();
        FormSuaXoaSP_admin.jplnen.add(new SuaSP());
        FormSuaXoaSP_admin.jplnen.repaint();
        FormSuaXoaSP_admin.jplnen.updateUI();

        this.dispose();
    }//GEN-LAST:event_tblDanhSachSPMousePressed

    private void lblCloseButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseButtonMousePressed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_lblCloseButtonMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhSachSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhSachSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhSachSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhSachSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DanhSachSP dialog = new DanhSachSP(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCloseButton;
    private javax.swing.JTable tblDanhSachSP;
    // End of variables declaration//GEN-END:variables
}
