/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhom3.qlcf.view.form.banhang;

import com.nhom3.qlcf.helper.JDBCHelper;
import com.nhom3.qlcf.model.HoaDon;
import com.nhom3.qlcf.model.KhachHang;
import com.nhom3.qlcf.model.SanPham;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.TimerTask;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author baotri1998
 */
public class CapNhatHoaDon extends javax.swing.JDialog {

    /**
     * Creates new form CapNhatHoaDon
     */
    List<HoaDon> listHD = null;
    DefaultTableModel model;
    int index = 0;

    public CapNhatHoaDon(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        tblHoaDonChuThanhToan.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
        tblHoaDonChuThanhToan.setFont(new Font("Tohoma", Font.PLAIN, 12));
        tblHoaDonChuThanhToan.getTableHeader().setOpaque(false);
        tblHoaDonChuThanhToan.getTableHeader().setBackground(new Color(0, 0, 0));
        tblHoaDonChuThanhToan.getTableHeader().setForeground(new Color(255, 255, 255));
        tblHoaDonChuThanhToan.setRowHeight(25);
        filltoTable();
    }

    public void filltoTable() {

        ResultSet rs = JDBCHelper.executeQuery("EXEC dbo. HoaDonChuaThanhToan");
        model = (DefaultTableModel) tblHoaDonChuThanhToan.getModel();

        listHD = new ArrayList<HoaDon>();
        listHD.clear();
        try {
            model.setRowCount(0);
            while (rs.next()) {
                HoaDon hd = new HoaDon();
                KhachHang kh = new KhachHang();
                kh.setTenKh(rs.getString(5));
                kh.setDienThoai(rs.getString(7));
                hd.setMaHoaDon(rs.getString(1));
                hd.setMaKhachHang(kh);
                hd.setTongTien(rs.getDouble(8));
                hd.setTrangThai(rs.getBoolean(9));
                Object[] row = new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getDouble(4),
                    rs.getString(5), rs.getString(6), rs.getString(7), rs.getDouble(8), rs.getBoolean(9) == false ? "Chưa Thanh toán" : "Thanh Toán"};
                model.addRow(row);
                listHD.add(hd);

            }

        } catch (Exception e) {
            System.out.println(e);
        }
    }

    //
    public void update() {
        JDBCHelper.executeUpdate("UPDATE dbo.HoaDon SET trangThai = 1 WHERE maHD ='" + lblmaHD.getName() + "'");

        if (listHD.isEmpty()) {
            lblThongBao.setText("Không Có Hóa Đơn Nào!");
            lblThongBao.setForeground(Color.red);
        } else if (lblmaHD.getText().equals("Mã HĐ: ")) {
            lblThongBao.setText("Chọn Hóa Đơn Để Thanh Toán!");
            lblThongBao.setForeground(Color.red);
        } else {
            lblThongBao.setText("Thanh Toán Thành Công !");
            lblThongBao.setForeground(Color.green);
            filltoTable();
            lblmaHD.setText("Mã HĐ: ");
            lblKH.setText("");
            lblsdt.setText("");
            lbltongtien.setText("");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHoaDonChuThanhToan = new javax.swing.JTable();
        lblthanhToan = new javax.swing.JLabel();
        lblmaHD = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblThongBao = new javax.swing.JLabel();
        lblKH = new javax.swing.JLabel();
        lblsdt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbltongtien = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tblHoaDonChuThanhToan.setForeground(new java.awt.Color(51, 51, 51));
        tblHoaDonChuThanhToan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "Sản Phẩm", "Size", "Giá", "Anh/Chị", "Địa Chỉ", "SĐT"
            }
        ));
        tblHoaDonChuThanhToan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblHoaDonChuThanhToan.setFocusable(false);
        tblHoaDonChuThanhToan.setGridColor(new java.awt.Color(0, 0, 0));
        tblHoaDonChuThanhToan.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblHoaDonChuThanhToan.setRowHeight(25);
        tblHoaDonChuThanhToan.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblHoaDonChuThanhToan.setShowHorizontalLines(false);
        tblHoaDonChuThanhToan.setShowVerticalLines(false);
        tblHoaDonChuThanhToan.setSurrendersFocusOnKeystroke(true);
        tblHoaDonChuThanhToan.getTableHeader().setReorderingAllowed(false);
        tblHoaDonChuThanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblHoaDonChuThanhToanMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblHoaDonChuThanhToan);

        lblthanhToan.setBackground(new java.awt.Color(0, 102, 255));
        lblthanhToan.setForeground(new java.awt.Color(255, 255, 255));
        lblthanhToan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblthanhToan.setText("Chọn Hóa Đơn Thanh Toán");
        lblthanhToan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblthanhToan.setOpaque(true);
        lblthanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblthanhToanMousePressed(evt);
            }
        });

        lblmaHD.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblmaHD.setForeground(new java.awt.Color(0, 51, 255));
        lblmaHD.setText("Mã HĐ: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Close");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        lblThongBao.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lblThongBao.setForeground(new java.awt.Color(0, 255, 0));

        lblKH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblKH.setForeground(new java.awt.Color(0, 204, 0));

        lblsdt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblsdt.setForeground(new java.awt.Color(0, 51, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Khách Đặt Trên Web");

        lbltongtien.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(640, 640, 640)
                .addComponent(lblThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblmaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(lblKH, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lbltongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(lblthanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblmaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKH, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblthanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbltongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblHoaDonChuThanhToanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonChuThanhToanMousePressed
        // TODO add your handling code here:
        index = tblHoaDonChuThanhToan.getSelectedRow();
        HoaDon hd = listHD.get(index);
        lblmaHD.setText("Mã HĐ:" + hd.getMaHoaDon());
        lblKH.setText("Anh/Chị: " + hd.getMaKhachHang().getTenKh());
        lblsdt.setText("SĐT: " + hd.getMaKhachHang().getDienThoai());
        lbltongtien.setText("Tổng Tiền : " + hd.getTongTien());
        lblmaHD.setName(hd.getMaHoaDon());
        lblthanhToan.setText("Thanh Toán Ngay");

        //cbxTrangThai.setSelectedItem(hd.isTrangThai());
    }//GEN-LAST:event_tblHoaDonChuThanhToanMousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel2MousePressed

    private void lblthanhToanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblthanhToanMousePressed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_lblthanhToanMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CapNhatHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CapNhatHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CapNhatHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CapNhatHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CapNhatHoaDon dialog = new CapNhatHoaDon(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblKH;
    private javax.swing.JLabel lblThongBao;
    private javax.swing.JLabel lblmaHD;
    private javax.swing.JLabel lblsdt;
    private javax.swing.JLabel lblthanhToan;
    private javax.swing.JLabel lbltongtien;
    private javax.swing.JTable tblHoaDonChuThanhToan;
    // End of variables declaration//GEN-END:variables
}
