/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhom3.qlcf.view.form.banhang;

import com.nhom3.qlcf.dao.CTHoaDonDAO;
import com.nhom3.qlcf.dao.HoaDonDAO;
import com.nhom3.qlcf.dao.KhachHangDAO;
import com.nhom3.qlcf.dao.SanPhamDAO;
import com.nhom3.qlcf.helper.Designhelper;
import com.nhom3.qlcf.helper.JDBCHelper;
import com.nhom3.qlcf.helper.Loginhelper;
import com.nhom3.qlcf.helper.ReSizehelper;
import com.nhom3.qlcf.helper.Soundhelper;
import com.nhom3.qlcf.helper.Timehelper;
import com.nhom3.qlcf.helper.XuLy;
import com.nhom3.qlcf.model.CTHoaDon;
import com.nhom3.qlcf.model.HoaDon;
import com.nhom3.qlcf.model.KhachHang;
import com.nhom3.qlcf.model.NguoiDung;
import com.nhom3.qlcf.model.SanPham;
import com.nhom3.qlcf.test.testSQL;
import com.nhom3.qlcf.view.form.login.FormLogin;
import com.nhom3.qlcf.view.Run;
import com.nhom3.qlcf.view.form.khachhang.FormKhachHang;
import static com.nhom3.qlcf.view.form.khachhang.FormKhachHang.jpnDangKyForm;
import com.nhom3.qlcf.view.form.khachhang.ThemKH;
import com.nhom3.qlcf.view.form.khachhang.jdialogThemKH;
import com.nhom3.qlcf.view.form.login.Login;
import com.nhom3.qlcf.view.form.menu.FormMenu;
import static com.nhom3.qlcf.view.form.menu.FormMenu.jfMain;
import com.nhom3.qlcf.view.form.nhacungcap.FormDanhSachNhaCC;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author baotri1998
 */
public class FormBanHang extends javax.swing.JPanel {

    /**
     * Creates new form FormLogin
     */
    public static FormBanHang banhang;
    public static List<SanPham> list = new ArrayList<>();
    public static List<CTHoaDon> DongCTHD = new ArrayList<>();
    public static List<HoaDon> SavehoaDon = new ArrayList<>();
    public static List<HoaDon> hd = new ArrayList<>();
    NumberFormat chuyentien = new DecimalFormat("#,###,###");
    int so, diem;

    public FormBanHang() {
        initComponents();
        // jpnLogin1.setBackground(new Color(0, 0, 0, 134));
        //jpnNenButton_login1.setBackground(new Color(0, 0, 0, 64));
        banhang = this;
        LoadDataSanPham();
        getTongTien();
        CountSoLuongHoaDonTrenWeb();
        RezieImageGroupLogo();
        new Loginhelper().getLogin(lblUsers);
        lblbuton_thanhToan.setName(AutogetMaHD());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfBangHang = new javax.swing.JPanel();
        jpnShowMenuOut = new javax.swing.JPanel();
        jpnQuayVeBanHang = new javax.swing.JPanel();
        lblQuayVeBangHang = new javax.swing.JLabel();
        jpnTenDangNhapBanHang = new javax.swing.JPanel();
        lblUsers = new javax.swing.JLabel();
        jpnDangXuatBanHang = new javax.swing.JPanel();
        lblDangXuatBangHang = new javax.swing.JLabel();
        jpnToolbar19 = new javax.swing.JPanel();
        lblAn_BanHang = new javax.swing.JLabel();
        lblOutBangHang = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblfee = new javax.swing.JLabel();
        lblorderweb = new javax.swing.JLabel();
        lblShoworderweb = new javax.swing.JLabel();
        lblcoffe = new javax.swing.JLabel();
        lblbanhmi = new javax.swing.JLabel();
        lbltea = new javax.swing.JLabel();
        lblbanhngot = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jplDonHang = new javax.swing.JPanel();
        jSDonHang = new javax.swing.JScrollPane();
        jpldonhang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jplHoaDon = new javax.swing.JPanel();
        lbltenKH = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTimSDT = new javax.swing.JTextField();
        lblTamTinh = new javax.swing.JLabel();
        lblThanhTien = new javax.swing.JLabel();
        lbltimSDT = new javax.swing.JLabel();
        txtChietKhau = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtdiem = new javax.swing.JTextField();
        lbldiem = new javax.swing.JLabel();
        lbldiemtichluy = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txttienkhach = new javax.swing.JTextField();
        lbltenTienthua = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblbuton_thanhToan = new javax.swing.JLabel();
        lbltienthua = new javax.swing.JLabel();
        lblVienTxt = new javax.swing.JLabel();
        jpnNext = new javax.swing.JPanel();
        jSSanPham = new javax.swing.JScrollPane();
        jpnDSsanpham = new javax.swing.JPanel();
        lblThongBao = new javax.swing.JLabel();
        lblsound = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Card = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jfBangHang.setBackground(new java.awt.Color(255, 255, 255));
        jfBangHang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jfBangHang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnShowMenuOut.setBackground(new java.awt.Color(255, 255, 255));
        jpnShowMenuOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255)));
        jpnShowMenuOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpnShowMenuOutMouseExited(evt);
            }
        });
        jpnShowMenuOut.setLayout(null);

        jpnQuayVeBanHang.setBackground(new java.awt.Color(255, 255, 255));

        lblQuayVeBangHang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblQuayVeBangHang.setForeground(new java.awt.Color(51, 102, 255));
        lblQuayVeBangHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuayVeBangHang.setText("Quay Về");
        lblQuayVeBangHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblQuayVeBangHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuayVeBangHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblQuayVeBangHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuayVeBangHangMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpnQuayVeBanHangLayout = new javax.swing.GroupLayout(jpnQuayVeBanHang);
        jpnQuayVeBanHang.setLayout(jpnQuayVeBanHangLayout);
        jpnQuayVeBanHangLayout.setHorizontalGroup(
            jpnQuayVeBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQuayVeBangHang, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jpnQuayVeBanHangLayout.setVerticalGroup(
            jpnQuayVeBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblQuayVeBangHang, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jpnShowMenuOut.add(jpnQuayVeBanHang);
        jpnQuayVeBanHang.setBounds(10, 90, 150, 40);

        jpnTenDangNhapBanHang.setBackground(new java.awt.Color(255, 255, 255));

        lblUsers.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUsers.setForeground(new java.awt.Color(51, 102, 255));
        lblUsers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsers.setText("Tên NV");
        lblUsers.setToolTipText("ND001");
        lblUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUsersMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpnTenDangNhapBanHangLayout = new javax.swing.GroupLayout(jpnTenDangNhapBanHang);
        jpnTenDangNhapBanHang.setLayout(jpnTenDangNhapBanHangLayout);
        jpnTenDangNhapBanHangLayout.setHorizontalGroup(
            jpnTenDangNhapBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUsers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jpnTenDangNhapBanHangLayout.setVerticalGroup(
            jpnTenDangNhapBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblUsers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jpnShowMenuOut.add(jpnTenDangNhapBanHang);
        jpnTenDangNhapBanHang.setBounds(10, 9, 150, 40);

        jpnDangXuatBanHang.setBackground(new java.awt.Color(255, 255, 255));

        lblDangXuatBangHang.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDangXuatBangHang.setForeground(new java.awt.Color(51, 102, 255));
        lblDangXuatBangHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangXuatBangHang.setText("Đăng Xuất");
        lblDangXuatBangHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDangXuatBangHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangXuatBangHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDangXuatBangHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDangXuatBangHangMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jpnDangXuatBanHangLayout = new javax.swing.GroupLayout(jpnDangXuatBanHang);
        jpnDangXuatBanHang.setLayout(jpnDangXuatBanHangLayout);
        jpnDangXuatBanHangLayout.setHorizontalGroup(
            jpnDangXuatBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDangXuatBangHang, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        jpnDangXuatBanHangLayout.setVerticalGroup(
            jpnDangXuatBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDangXuatBangHang, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jpnShowMenuOut.add(jpnDangXuatBanHang);
        jpnDangXuatBanHang.setBounds(10, 50, 150, 40);

        jfBangHang.add(jpnShowMenuOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 170, 140));
        jpnShowMenuOut.hide();

        jpnToolbar19.setBackground(new java.awt.Color(255, 255, 255));
        jpnToolbar19.setOpaque(false);

        lblAn_BanHang.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lblAn_BanHang.setForeground(new java.awt.Color(255, 255, 255));
        lblAn_BanHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAn_BanHang.setText("-");
        lblAn_BanHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAn_BanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAn_BanHangMouseClicked(evt);
            }
        });

        lblOutBangHang.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblOutBangHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOutBangHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/logout.png"))); // NOI18N
        lblOutBangHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOutBangHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOutBangHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblOutBangHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblOutBangHangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblOutBangHangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblOutBangHangMouseReleased(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tìm Kiếm");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTimKiem)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        txtTimKiem.setText("Tìm kiếm");
        txtTimKiem.setForeground(Color.gray);
        XuLy.placeHolder(txtTimKiem, "Tìm kiếm");

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setOpaque(false);
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblfee.setBackground(new java.awt.Color(255, 255, 255));
        lblfee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblfee.setToolTipText("Freeze");
        lblfee.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblfee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblfee.setName("ML005"); // NOI18N
        lblfee.setOpaque(true);
        lblfee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblfeeMousePressed(evt);
            }
        });
        jPanel9.add(lblfee, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 80, 40));

        lblorderweb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblorderweb.setForeground(new java.awt.Color(255, 0, 0));
        lblorderweb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblorderweb.setText("0");
        lblorderweb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblorderweb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblorderwebMousePressed(evt);
            }
        });
        jPanel9.add(lblorderweb, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 40, 10));

        lblShoworderweb.setBackground(new java.awt.Color(255, 255, 255));
        lblShoworderweb.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblShoworderweb.setForeground(new java.awt.Color(255, 255, 255));
        lblShoworderweb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShoworderweb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/cartWeb.png"))); // NOI18N
        lblShoworderweb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblShoworderweb.setOpaque(true);
        lblShoworderweb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblShoworderwebMousePressed(evt);
            }
        });
        jPanel9.add(lblShoworderweb, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 50, 40));

        lblcoffe.setBackground(new java.awt.Color(255, 255, 255));
        lblcoffe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcoffe.setToolTipText("Cà Phê");
        lblcoffe.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblcoffe.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblcoffe.setName("ML001"); // NOI18N
        lblcoffe.setOpaque(true);
        lblcoffe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblcoffeMousePressed(evt);
            }
        });
        jPanel9.add(lblcoffe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 40));

        lblbanhmi.setBackground(new java.awt.Color(255, 255, 255));
        lblbanhmi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbanhmi.setToolTipText("Bánh");
        lblbanhmi.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblbanhmi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblbanhmi.setName("ML003"); // NOI18N
        lblbanhmi.setOpaque(true);
        lblbanhmi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblbanhmiMousePressed(evt);
            }
        });
        jPanel9.add(lblbanhmi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 80, 40));

        lbltea.setBackground(new java.awt.Color(255, 255, 255));
        lbltea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltea.setToolTipText("Trà ");
        lbltea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbltea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbltea.setName("ML002"); // NOI18N
        lbltea.setOpaque(true);
        lbltea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblteaMousePressed(evt);
            }
        });
        jPanel9.add(lbltea, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 80, 40));

        lblbanhngot.setBackground(new java.awt.Color(255, 255, 255));
        lblbanhngot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbanhngot.setToolTipText("Bánh Ngọt");
        lblbanhngot.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblbanhngot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblbanhngot.setName("ML004"); // NOI18N
        lblbanhngot.setOpaque(true);
        lblbanhngot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblbanhngotMousePressed(evt);
            }
        });
        jPanel9.add(lblbanhngot, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 80, 40));

        jLabel6.setBackground(new java.awt.Color(0, 102, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("LOAD");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setOpaque(true);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 50, 40));

        javax.swing.GroupLayout jpnToolbar19Layout = new javax.swing.GroupLayout(jpnToolbar19);
        jpnToolbar19.setLayout(jpnToolbar19Layout);
        jpnToolbar19Layout.setHorizontalGroup(
            jpnToolbar19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnToolbar19Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblAn_BanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOutBangHang)
                .addGap(17, 17, 17))
        );
        jpnToolbar19Layout.setVerticalGroup(
            jpnToolbar19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblAn_BanHang, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jpnToolbar19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnToolbar19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addComponent(lblOutBangHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jfBangHang.add(jpnToolbar19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jplDonHang.setBackground(new java.awt.Color(255, 255, 255));

        jSDonHang.setBackground(Color.decode("#e6e6e6"));
        jSDonHang.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSDonHang.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jpldonhang.setBackground(new java.awt.Color(255, 255, 255));
        jpldonhang.setAutoscrolls(true);
        jpldonhang.setMaximumSize(new java.awt.Dimension(32767, 400));

        javax.swing.GroupLayout jpldonhangLayout = new javax.swing.GroupLayout(jpldonhang);
        jpldonhang.setLayout(jpldonhangLayout);
        jpldonhangLayout.setHorizontalGroup(
            jpldonhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1109, Short.MAX_VALUE)
        );
        jpldonhangLayout.setVerticalGroup(
            jpldonhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );

        jSDonHang.setViewportView(jpldonhang);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("#Mã/TênSP                                             Giá Niêm Yết                                                   Thành Tiền  /SL            ");
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout jplDonHangLayout = new javax.swing.GroupLayout(jplDonHang);
        jplDonHang.setLayout(jplDonHangLayout);
        jplDonHangLayout.setHorizontalGroup(
            jplDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jplDonHangLayout.setVerticalGroup(
            jplDonHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplDonHangLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSDonHang, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jplHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        jplHoaDon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbltenKH.setBackground(new java.awt.Color(255, 255, 255));
        lbltenKH.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lbltenKH.setForeground(new java.awt.Color(0, 51, 204));
        lbltenKH.setText(" x Khách lẻ");
        lbltenKH.setToolTipText("Khach le");
        lbltenKH.setOpaque(true);
        jplHoaDon.add(lbltenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 43, 174, -1));
        lbltenKH.setName("KH000");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Tạm Tính:");
        jLabel5.setToolTipText("1");
        jplHoaDon.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, 116, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Chiết Khấu:");
        jplHoaDon.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 98, -1, 25));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("Tổng Thành Tiền: ");
        jplHoaDon.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 133, 116, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel11.setText("Ngày tạo:");
        jplHoaDon.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 40, 100, -1));

        txtTimSDT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimSDTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimSDTFocusLost(evt);
            }
        });
        txtTimSDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtTimSDTMouseEntered(evt);
            }
        });
        jplHoaDon.add(txtTimSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 215, 31));
        txtTimSDT.setText("Tìm SĐT KH");
        txtTimSDT.setForeground(Color.gray);
        XuLy.placeHolder(txtTimSDT, "Tìm SĐT KH");

        lblTamTinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTamTinh.setText("....");
        jplHoaDon.add(lblTamTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 120, 30));

        lblThanhTien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblThanhTien.setText("0 VNĐ");
        jplHoaDon.add(lblThanhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 129, 143, 23));

        lbltimSDT.setBackground(new java.awt.Color(0, 51, 255));
        lbltimSDT.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltimSDT.setForeground(new java.awt.Color(255, 255, 255));
        lbltimSDT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltimSDT.setText("Tìm Kiếm");
        lbltimSDT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbltimSDT.setOpaque(true);
        lbltimSDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbltimSDTMousePressed(evt);
            }
        });
        jplHoaDon.add(lbltimSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 0, 72, 31));

        txtChietKhau.setEditable(false);
        txtChietKhau.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtChietKhau.setText("0");
        txtChietKhau.setOpaque(false);
        txtChietKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChietKhauActionPerformed(evt);
            }
        });
        jplHoaDon.add(txtChietKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 50, 20));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("%");
        jplHoaDon.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 20, 20));

        jLabel13.setBackground(new java.awt.Color(0, 102, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("-");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.setOpaque(true);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });
        jplHoaDon.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 30, 20));

        jLabel15.setBackground(new java.awt.Color(0, 51, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("+");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.setOpaque(true);
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });
        jplHoaDon.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 30, 20));

        txtdiem.setEditable(false);
        txtdiem.setText("0");
        txtdiem.setName("true"); // NOI18N
        jplHoaDon.add(txtdiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 60, -1));
        txtdiem.hide();

        lbldiem.setBackground(new java.awt.Color(0, 51, 255));
        lbldiem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbldiem.setForeground(new java.awt.Color(255, 255, 255));
        lbldiem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldiem.setText("Điểm");
        lbldiem.setOpaque(true);
        jplHoaDon.add(lbldiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 40, 20));
        lbldiem.hide();

        lbldiemtichluy.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbldiemtichluy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldiemtichluy.setText("0");
        lbldiemtichluy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        lbldiemtichluy.setName("true"); // NOI18N
        jplHoaDon.add(lbldiemtichluy, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 50, 20));

        jLabel4.setBackground(new java.awt.Color(0, 51, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Điểm +:");
        jLabel4.setOpaque(true);
        jplHoaDon.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 50, 20));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 255));
        jLabel9.setText("Tiền Khách Trả:");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 14, -1, 34));

        txttienkhach.setText("0");
        txttienkhach.setBorder(null);
        txttienkhach.setOpaque(false);
        txttienkhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttienkhachActionPerformed(evt);
            }
        });
        txttienkhach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttienkhachKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txttienkhachKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttienkhachKeyTyped(evt);
            }
        });
        jPanel7.add(txttienkhach, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 15, 155, 34));

        lbltenTienthua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltenTienthua.setForeground(new java.awt.Color(51, 0, 255));
        lbltenTienthua.setText("Tiềm Thừa:");
        jPanel7.add(lbltenTienthua, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 55, 93, 27));

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));

        lblbuton_thanhToan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblbuton_thanhToan.setForeground(new java.awt.Color(255, 255, 255));
        lblbuton_thanhToan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbuton_thanhToan.setText("THANH TOÁN");
        lblbuton_thanhToan.setToolTipText("AutogetMaHD");
        lblbuton_thanhToan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblbuton_thanhToan.setName("AutogetMaHD"); // NOI18N
        lblbuton_thanhToan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblbuton_thanhToanMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblbuton_thanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblbuton_thanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 93, 230, 51));

        lbltienthua.setBackground(new java.awt.Color(255, 255, 255));
        lbltienthua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbltienthua.setForeground(new java.awt.Color(0, 0, 255));
        lbltienthua.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbltienthua.setText("0");
        lbltienthua.setOpaque(true);
        jPanel7.add(lbltienthua, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 55, 155, 27));

        lblVienTxt.setForeground(new java.awt.Color(0, 102, 255));
        lblVienTxt.setText("_________________________");
        jPanel7.add(lblVienTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 24, 150, 30));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jplHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpnNext.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpnNextLayout = new javax.swing.GroupLayout(jpnNext);
        jpnNext.setLayout(jpnNextLayout);
        jpnNextLayout.setHorizontalGroup(
            jpnNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 342, Short.MAX_VALUE)
        );
        jpnNextLayout.setVerticalGroup(
            jpnNextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jSSanPham.setBackground(Color.decode("#e6e6e6"));
        jSSanPham.setBorder(null);
        jSSanPham.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jpnDSsanpham.setBackground(new java.awt.Color(255, 255, 255));
        jpnDSsanpham.setAutoscrolls(true);
        jpnDSsanpham.setMaximumSize(new java.awt.Dimension(32767, 400));
        jpnDSsanpham.setLayout(new javax.swing.BoxLayout(jpnDSsanpham, javax.swing.BoxLayout.LINE_AXIS));
        jSSanPham.setViewportView(jpnDSsanpham);

        lblThongBao.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblThongBao.setForeground(new java.awt.Color(255, 0, 51));
        lblThongBao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblsound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/sound.png"))); // NOI18N
        lblsound.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblsound.setName("sound"); // NOI18N
        lblsound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblsoundMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jplDonHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(lblThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jpnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblsound)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblsound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jpnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jplDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        lblsound.setName("sound");

        jfBangHang.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 1070, 620));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/nenThuNgan.png"))); // NOI18N
        jfBangHang.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, -1));

        add(jfBangHang);

        Card.setBackground(new java.awt.Color(255, 255, 255));
        Card.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        Card.setLayout(new java.awt.CardLayout());
        add(Card);
    }// </editor-fold>//GEN-END:initComponents

    private void lblAn_BanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAn_BanHangMouseClicked
        // TODO add your handling code here:
        Run.main.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblAn_BanHangMouseClicked

    private void lblOutBangHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOutBangHangMouseClicked
        // TODO add your handling code here:
        jpnShowMenuOut.show();
        lblOutBangHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/logout.png")));
    }//GEN-LAST:event_lblOutBangHangMouseClicked

    private void lblOutBangHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOutBangHangMouseEntered
        // TODO add your handling code here:
        lblOutBangHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/logout_hover.png")));
    }//GEN-LAST:event_lblOutBangHangMouseEntered

    private void lblOutBangHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOutBangHangMouseExited
        // TODO add your handling code here:
        lblOutBangHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/logout.png")));
    }//GEN-LAST:event_lblOutBangHangMouseExited

    private void lblOutBangHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOutBangHangMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOutBangHangMousePressed

    private void lblOutBangHangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOutBangHangMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOutBangHangMouseReleased

    private void lblQuayVeBangHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuayVeBangHangMouseClicked
        // TODO add your handling code here:
        if (DongCTHD.isEmpty()) {
            new Loginhelper().QuayVe();
        } else {

            lblThongBao.setText("Hãy Thanh Toán Hóa Đơn Trước Khi Rời Khỏi");
            jpnShowMenuOut.hide();
        }


        /*jpnDangXuat.setBackground(Color.white);
        lblDangXuat.setForeground(new Color(51, 102, 255));
        jpnBanHang_Button.setBackground(new Color(0, 0, 0));
        jpnBanHang_Button.setOpaque(false);
        lblBanHang_txt.setForeground(Color.WHITE);*/
        jpnQuayVeBanHang.setBackground(Color.white);
        lblQuayVeBangHang.setForeground(new Color(51, 102, 255));
    }//GEN-LAST:event_lblQuayVeBangHangMouseClicked

    private void lblQuayVeBangHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuayVeBangHangMouseEntered
        // TODO add your handling code here:
        jpnQuayVeBanHang.setBackground(new Color(51, 102, 255));
        lblQuayVeBangHang.setForeground(Color.white);
        jpnShowMenuOut.show();
    }//GEN-LAST:event_lblQuayVeBangHangMouseEntered

    private void lblQuayVeBangHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuayVeBangHangMouseExited
        // TODO add your handling code here:
        jpnQuayVeBanHang.setBackground(Color.white);
        lblQuayVeBangHang.setForeground(new Color(51, 102, 255));
    }//GEN-LAST:event_lblQuayVeBangHangMouseExited

    private void lblUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsersMouseEntered
        // TODO add your handling code here:
        jpnTenDangNhapBanHang.setBackground(new Color(51, 102, 255));
        lblUsers.setForeground(Color.white);
        jpnShowMenuOut.show();
    }//GEN-LAST:event_lblUsersMouseEntered

    private void lblUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsersMouseExited
        // TODO add your handling code here:

        jpnTenDangNhapBanHang.setBackground(Color.white);
        lblUsers.setForeground(new Color(51, 102, 255));
    }//GEN-LAST:event_lblUsersMouseExited

    private void lblDangXuatBangHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatBangHangMouseClicked
        // TODO add your handling code here:
        FormLogin.login.Card.removeAll();
        FormLogin.login.Card.add(FormLogin.login.jfLogin);
        FormLogin.login.Card.repaint();
        FormLogin.login.Card.revalidate();
        FormLogin.login.Card.show();
        jfMain.hide();
        jfBangHang.hide();
        /* jpnNenButton_login.setBackground(new Color(0, 0, 0));
        jpnNenButton_login.setOpaque(false);
        lblLogin.setForeground(Color.white);
        jpnDangXuat.setBackground(Color.white);
        lblDangXuat.setForeground(new Color(51, 102, 255));*/
        jpnShowMenuOut.hide();
        Login.txtPass.setText("");
        Login.lblLoiDangNhap.hide();
        jpnDangXuatBanHang.setBackground(Color.white);
        lblDangXuatBangHang.setForeground(new Color(51, 102, 255));
    }//GEN-LAST:event_lblDangXuatBangHangMouseClicked

    private void lblDangXuatBangHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatBangHangMouseEntered
        // TODO add your handling code here:

        jpnDangXuatBanHang.setBackground(new Color(51, 102, 255));
        lblDangXuatBangHang.setForeground(Color.white);
        jpnShowMenuOut.show();
    }//GEN-LAST:event_lblDangXuatBangHangMouseEntered

    private void lblDangXuatBangHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatBangHangMouseExited
        // TODO add your handling code here:

        jpnDangXuatBanHang.setBackground(Color.white);
        lblDangXuatBangHang.setForeground(new Color(51, 102, 255));
    }//GEN-LAST:event_lblDangXuatBangHangMouseExited

    private void jpnShowMenuOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpnShowMenuOutMouseExited
        // TODO add your handling code here:
        jpnShowMenuOut.hide();
    }//GEN-LAST:event_jpnShowMenuOutMouseExited

    private void lblbuton_thanhToanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbuton_thanhToanMousePressed
        // TODO add your handling code here:
        String opObjects[] = {"Tiếp tục", "Quay Lại"};
        if (!DongCTHD.isEmpty() || !SavehoaDon.isEmpty()) {

            if (!txttienkhach.getText().trim().equals("") && !lbltienthua.getText().equals("0") || 0 == JOptionPane.showOptionDialog(null,
                    "Cảnh báo, bạn chưa nhập tiền khách trả hoặc chưa quy ra tiền thối, vẫn tiếp tục?",
                    "Cảnh Báo!",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.INFORMATION_MESSAGE,
                    null,
                    opObjects,
                    opObjects[0])) {
                GetHD();
                DongGoiHD();
                InsertHD();
                InsertHDCT();
                updateDiem();
                Designhelper designhelper = new Designhelper();
                designhelper.DesigDonHang(jpldonhang, DongCTHD);
                lblThongBao.setText("Thanh Toán Thành Công!");
                lblThongBao.setForeground(Color.GREEN);
                if (txttienkhach.getText().trim().equals("")) {
                    txttienkhach.setText("0");
                    InHoaDon show = new InHoaDon(null, true, lblbuton_thanhToan.getToolTipText(), lblThanhTien.getToolTipText(), lbltenKH.getToolTipText(), txtdiem.getName(),
                            txttienkhach.getText(), lbltienthua.getText(), txtChietKhau.getText());
                    show.setVisible(true);
                } else {
                    InHoaDon show = new InHoaDon(null, true, lblbuton_thanhToan.getToolTipText(), lblThanhTien.getToolTipText(), lbltenKH.getToolTipText(), txtdiem.getName(),
                            txttienkhach.getText(), lbltienthua.getText(), txtChietKhau.getText());
                    show.setVisible(true);
                }

                Reset();

            }

        } else {
            lblThongBao.setText("Không có hóa đơn để thanh toán, thử lại!");
            lblThongBao.setForeground(Color.red);
        }

    }//GEN-LAST:event_lblbuton_thanhToanMousePressed

    private void txttienkhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttienkhachActionPerformed
        // TODO add your handling code here:

        if (CheckTienKhach()) {

            int tienThoi = 0;
            tienThoi += Double.parseDouble(txttienkhach.getText()) - Double.parseDouble(lblThanhTien.getToolTipText());

            if (Double.parseDouble(txttienkhach.getText()) < Double.parseDouble(lblThanhTien.getToolTipText())) {
                lbltienthua.setForeground(Color.red);
                lbltenTienthua.setText("Tiền Thiếu: ");
                lbltienthua.setText(String.valueOf(chuyentien.format(tienThoi)) + "  VNĐ");
            } else if (Double.parseDouble(txttienkhach.getText()) == 0) {
                lbltienthua.setForeground(Color.black);
                lbltenTienthua.setText("Tiền Thối: ");
                lbltienthua.setText("0 VNĐ");
            } else {

                lbltienthua.setForeground(Color.black);
                lbltenTienthua.setText("Tiền Thối: ");
                lbltienthua.setText(String.valueOf(chuyentien.format(tienThoi)) + "  VNĐ");
            }
        }

    }//GEN-LAST:event_txttienkhachActionPerformed

    private void txtChietKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChietKhauActionPerformed
        // TODO add your handling code here:
        GetHD();
        DongGoiHD();
        getTongTien();
    }//GEN-LAST:event_txtChietKhauActionPerformed
    KhachHang nd = null;
    private void lbltimSDTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltimSDTMousePressed
        // TODO add your handling code here:
        KhachHangDAO khDao = new KhachHangDAO();
        if (txtTimSDT.getText().trim().equals("") || txtTimSDT.getText().trim().equals("Tìm SĐT KH")) {
            lbltenKH.setText("Nhập số điện thoại khách hàng!");
            lbltenKH.setForeground(Color.red);
            lbltenKH.setCursor(null);
            lbltenKH.setName("KH000");
            txtTimSDT.requestFocus();
            txtdiem.hide();
            lbldiem.hide();
        } else if (!txtTimSDT.getText().matches("[0-9]+")) {
            lbltenKH.setText("Lỗi! phải nhập bằng số!");
            lbltenKH.setForeground(Color.red);
            lbltenKH.setCursor(null);
            lbltenKH.setName("KH000");
            txtdiem.hide();
            lbldiem.hide();
            txtTimSDT.requestFocus();
        } else if (txtTimSDT.getText().length() < 9 || txtTimSDT.getText().length() > 13) {
            lbltenKH.setText("SĐT phải là [9-13] số!");
            lbltenKH.setForeground(Color.red);
            lbltenKH.setCursor(null);
            lbltenKH.setName("KH000");
            txtdiem.hide();
            lbldiem.hide();
            txtTimSDT.requestFocus();
        } else if (khDao.checkSDT(txtTimSDT.getText()) == false) {
            lbltenKH.setText("SĐT này chưa đăng ký");
            lbltenKH.setForeground(Color.red);
            lbltenKH.setName("KH000");
            lbltenKH.setCursor(new Cursor(Cursor.HAND_CURSOR));
            lbltenKH.addMouseListener(new MouseAdapter() {
                @Override
                public void mousePressed(MouseEvent e) {
                    if (lbltenKH.getText().equals("SĐT này chưa đăng ký")) {
                        jdialogThemKH themKH = new jdialogThemKH(null, true, txtTimSDT.getText());
                        themKH.setVisible(true);

                    } else {

                    }

                }
            });
            txtdiem.hide();
            lbldiem.hide();
        } else {

            searchSDT();
        }
        diemtichluy();

    }//GEN-LAST:event_lbltimSDTMousePressed

    private void txtTimSDTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTimSDTMouseEntered
        // TODO add your handling code here:


    }//GEN-LAST:event_txtTimSDTMouseEntered

    private void txtTimSDTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimSDTFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTimSDTFocusGained

    private void txtTimSDTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimSDTFocusLost
        // TODO add your handling code here:


    }//GEN-LAST:event_txtTimSDTFocusLost
    public void ChietKhauTang() {
        so = Integer.parseInt(txtChietKhau.getText());
        int diem = Integer.parseInt(txtdiem.getText());
        if (lbldiemtichluy.getText().equals("0") && lbltenKH.getText().equals("KH000")) {
            KhachHangDAO khdao = new KhachHangDAO();
            nd = khdao.selectID(txtTimSDT.getText());
            txtdiem.setText(String.valueOf(nd.getDiemThuong()));
        }

        if (so < 100) {
            double tongtien = 0;
            for (int i = 0; i < DongCTHD.size(); i++) {
                tongtien += (DongCTHD.get(i).getMaHoaDon().getTongTien());
            }
            //khách tích lủy 1000 ms dc giảm giá, 
            if (!txtdiem.getText().equals("0") && so < 5 && diem > 500 && tongtien > 200000) {
                so++;
                txtChietKhau.setText(String.valueOf((so + 5) - 1));
                lbldiemtichluy.setText("0");
                int quydiem = Integer.parseInt(txtChietKhau.getText()) * 100;
                diem = quydiem - (Integer.parseInt(txtdiem.getText()));
                if (-diem >= 0) {
                    txtdiem.setText(String.valueOf(-(diem)));
                }
            } else {//
                if (lbltenKH.getText().equals(" x Khách lẻ")
                        || lbltenKH.getText().equals("SĐT này chưa đăng ký")
                        || lbltenKH.getText().equals("Nhập số điện thoại khách hàng!")
                        || lbltenKH.getText().equals("Lỗi! phải nhập bằng số!")
                        || lbltenKH.getText().equals("SĐT phải là [9-13] số!")) {
                    so++;
                    txtChietKhau.setText(String.valueOf((so + 5) - 1));
                }
            }
            getTongTien();

        }
    }
    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
        // TODO add your handling code here:
        ChietKhauTang();

    }//GEN-LAST:event_jLabel15MousePressed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        // TODO add your handling code here:

        so = Integer.parseInt(txtChietKhau.getText());
        if (so != 0 && so != 1) {
            so--;
            diemtichluy();
            diem = Integer.parseInt(txtChietKhau.getText()) * 100 + (Integer.parseInt(txtdiem.getText()));
            txtChietKhau.setText(String.valueOf(so - 4));
            txtdiem.setText(String.valueOf(diem));
            getTongTien();

        }
    }//GEN-LAST:event_jLabel13MousePressed

    private void lblShoworderwebMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShoworderwebMousePressed
        // TODO add your handling code here:
        if (!lblorderweb.getText().equals("0")) {
            lblThongBao.setText("");
            KhachDatOnline hd = new KhachDatOnline(null, true);
            hd.setVisible(true);
        } else {
            lblThongBao.setText("Không thể mở! vì chưa có hóa đơn online nào!");
            lblThongBao.setForeground(Color.red);
        }

    }//GEN-LAST:event_lblShoworderwebMousePressed

    private void lblcoffeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcoffeMousePressed
        // TODO add your handling code here:
        lblThongBao.setForeground(Color.GREEN);
        lblThongBao.setText("Đang Tải...");
        Click_Logo(lblcoffe);

    }//GEN-LAST:event_lblcoffeMousePressed

    private void lblteaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblteaMousePressed
        // TODO add your handling code here:

        lblThongBao.setForeground(Color.GREEN);
        lblThongBao.setText("Đang Tải...");
        Click_Logo(lbltea);
    }//GEN-LAST:event_lblteaMousePressed

    private void lblbanhmiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbanhmiMousePressed
        // TODO add your handling code here:
        lblThongBao.setForeground(Color.GREEN);
        lblThongBao.setText("Đang Tải...");
        Click_Logo(lblbanhmi);
    }//GEN-LAST:event_lblbanhmiMousePressed

    private void lblbanhngotMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbanhngotMousePressed
        // TODO add your handling code here:
        lblThongBao.setForeground(Color.GREEN);
        lblThongBao.setText("Đang Tải...");
        Click_Logo(lblbanhngot);
    }//GEN-LAST:event_lblbanhngotMousePressed

    private void lblfeeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblfeeMousePressed
        // TODO add your handling code here:
        lblThongBao.setForeground(Color.GREEN);
        lblThongBao.setText("Đang Tải...");
        Click_Logo(lblfee);
    }//GEN-LAST:event_lblfeeMousePressed

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
        // TODO add your handling code here:

        LoadDataSanPham();
    }//GEN-LAST:event_jLabel6MousePressed

    private void lblorderwebMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblorderwebMousePressed
        // TODO add your handling code here:
        Timehelper time = new Timehelper();
    }//GEN-LAST:event_lblorderwebMousePressed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:\
        lblThongBao.setForeground(Color.GREEN);
        lblThongBao.setText("Đang Tải...");
        Search(txtTimKiem);

    }//GEN-LAST:event_jLabel3MousePressed

    private void lblsoundMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblsoundMousePressed
        // TODO add your handling code here:

        if (lblsound.getName().equals("sound")) {
            lblsound.setName("mute");
            lblsound.setIcon(new ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/mute.png")));

        } else {
            lblsound.setName("sound");
            lblsound.setIcon(new ImageIcon(getClass().getResource("/com/nhom3/qlcf/img/sound.png")));

        }
    }//GEN-LAST:event_lblsoundMousePressed

    private void txttienkhachKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttienkhachKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txttienkhachKeyPressed

    private void txttienkhachKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttienkhachKeyTyped
        // TODO add your handling code here:
        if (txttienkhach.getText().equals("")) {
            lbltienthua.setForeground(Color.black);
            lbltenTienthua.setText("Tiền Thối: ");
            lbltienthua.setText("0 VNĐ");

        }

    }//GEN-LAST:event_txttienkhachKeyTyped
    public void tienKhach() {
        if (CheckTienKhach()) {

            int tienThoi = 0;
            tienThoi += Double.parseDouble(txttienkhach.getText()) - Double.parseDouble(lblThanhTien.getToolTipText());

            if (Double.parseDouble(txttienkhach.getText()) < Double.parseDouble(lblThanhTien.getToolTipText())) {
                lbltienthua.setForeground(Color.red);
                lbltenTienthua.setText("Tiền Thiếu: ");
                lbltienthua.setText(String.valueOf(chuyentien.format(tienThoi)) + "  VNĐ");
            } else if (Double.parseDouble(txttienkhach.getText()) == 0) {
                lbltienthua.setForeground(Color.black);
                lbltenTienthua.setText("Tiền Thối: ");
                lbltienthua.setText("0 VNĐ");
            } else if (txttienkhach.getText().equals("")) {
                lbltienthua.setForeground(Color.black);
                lbltenTienthua.setText("Tiền Thối: ");
                lbltienthua.setText("0 VNĐ");
            } else {

                lbltienthua.setForeground(Color.black);
                lbltenTienthua.setText("Tiền Thối: ");
                lbltienthua.setText(String.valueOf(chuyentien.format(tienThoi)) + "  VNĐ");
            }
        }
    }
    private void txttienkhachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttienkhachKeyReleased
        // TODO add your handling code here:
tienKhach();
    }//GEN-LAST:event_txttienkhachKeyReleased
    public void RezieImageGroupLogo() {
        try {
            BufferedImage HinhAnh, HinhAnh2, HinhAnh3, HinhAnh4, HinhAnh5;
            BufferedImage coffee = ImageIO.read(getClass().getResource("/com/nhom3/qlcf/img/Americano(44).png"));
            BufferedImage tea = ImageIO.read(getClass().getResource("/com/nhom3/qlcf/img/TraThachVai(39).png"));
            BufferedImage banhmi = ImageIO.read(getClass().getResource("/com/nhom3/qlcf/img/GaXeNuocTuong(19).png"));
            BufferedImage banhngot = ImageIO.read(getClass().getResource("/com/nhom3/qlcf/img/PhoMaiTraXanh(29).jpg"));
            BufferedImage fee = ImageIO.read(getClass().getResource("/com/nhom3/qlcf/img/FreezeChocolate(49).png"));
            int type = coffee.getType() == 0 ? BufferedImage.TYPE_INT_ARGB : coffee.getType();
            int type1 = tea.getType() == 0 ? BufferedImage.TYPE_INT_ARGB : tea.getType();
            int type2 = banhmi.getType() == 0 ? BufferedImage.TYPE_INT_ARGB : banhmi.getType();
            int type3 = banhngot.getType() == 0 ? BufferedImage.TYPE_INT_ARGB : banhngot.getType();
            int type4 = fee.getType() == 0 ? BufferedImage.TYPE_INT_ARGB : fee.getType();
            HinhAnh = new ReSizehelper().buffImage(coffee, type, 70, 60);
            HinhAnh2 = new ReSizehelper().buffImage(tea, type1, 60, 40);
            HinhAnh3 = new ReSizehelper().buffImage(banhmi, type2, 60, 50);
            HinhAnh4 = new ReSizehelper().buffImage(banhngot, type3, 60, 50);
            HinhAnh5 = new ReSizehelper().buffImage(fee, type4, 60, 40);
            ImageIcon icon = new ImageIcon(HinhAnh);
            ImageIcon icon2 = new ImageIcon(HinhAnh2);
            ImageIcon icon3 = new ImageIcon(HinhAnh3);
            ImageIcon icon4 = new ImageIcon(HinhAnh4);
            ImageIcon icon5 = new ImageIcon(HinhAnh5);
            lblcoffe.setIcon(icon);
            lbltea.setIcon(icon2);
            lblbanhmi.setIcon(icon3);
            lblbanhngot.setIcon(icon4);
            lblfee.setIcon(icon5);
        } catch (Exception e) {
        }

    }

    public void Click_Logo(JLabel lbllogo) {
        Timehelper timehelper = new Timehelper();
        timehelper.TimerLoad(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                lblThongBao.setText("");
                jpnDSsanpham.setLayout(new GridLayout(2, 3, 4, 4));
                int start = 0;
                int end = 8;
                // List Show sp từ dữ liệu SQL
                SanPhamDAO s = new SanPhamDAO();
                if (s.selecttheoLoai(lbllogo.getName()).size() < 8) {
                    end = s.selecttheoLoai(lbllogo.getToolTipText()).size();
                }
                Designhelper designhelper = new Designhelper();
                list = designhelper.LimitPage(s.selecttheoLoai(lbllogo.getName()), start, end);
                designhelper.DesignPage(jpnNext, s.selecttheoLoai(lbllogo.getName()));
                designhelper.DesignSanPham(jpnDSsanpham, s.selecttheoLoai(lbllogo.getName()));

                timehelper.t.stop();
            }
        });
    }

    public boolean CheckTienKhach() {
        String so = "[0-9]+";
        if (!txttienkhach.getText().matches(so)) {
            lblThongBao.setText("Tiền phải nhập bằng số!");
            return false;
        } else if (txttienkhach.getText().trim().equals("")) {
            lblThongBao.setText("Bạn cần nhập số tiền của khách hàng!!");
        }

        return true;
    }

    public void searchSDT() {
        KhachHangDAO khDao = new KhachHangDAO();
        lbltenKH.setCursor(new Cursor(Cursor.HAND_CURSOR));
        lbltenKH.setForeground(Color.BLUE);
        nd = khDao.selectID(txtTimSDT.getText());
        lbltenKH.setText(nd.getTenKh());
        txtdiem.setText(String.valueOf(nd.getDiemThuong()));
        txtdiem.setName(nd.getDienThoai());
        lbltenKH.setName(nd.getMakh());
        lbltenKH.setToolTipText(nd.getTenKh());
        lbldiemtichluy.setName(String.valueOf(nd.isTrangThai()));
        txtChietKhau.setText("0");
        txtdiem.show();
        lbldiem.show();
    }

    public void Search(JTextField Search) {
        Timehelper timehelper = new Timehelper();
        timehelper.TimerLoad(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                lblThongBao.setText("");
                jpnDSsanpham.setLayout(new GridLayout(2, 3, 4, 4));
                int start = 0;
                int end = 8;
                // List Show sp từ dữ liệu SQL
                SanPhamDAO s = new SanPhamDAO();
                if (s.selectSearch(Search.getText()).size() < 8) {
                    end = s.selectSearch(Search.getText()).size();
                }
                Designhelper designhelper = new Designhelper();
                list = designhelper.LimitPage(s.selectSearch(Search.getText()), start, end);
                designhelper.DesignPage(jpnNext, s.selectSearch(Search.getText()));
                designhelper.DesignSanPham(jpnDSsanpham, s.selectSearch(Search.getText()));

                timehelper.t.stop();
            }
        });
    }

    public void LoadDataSanPham() {

        try {
            jpnDSsanpham.setLayout(new GridLayout(9, 4, 3, 3));
            testSQL sql = new testSQL();
            int start = 0;
            int end = 9;
            // List Show sp từ dữ liệu SQL

            if (sql.select().size() < 9) {
                end = sql.select().size();
                //jpnDSsanpham.setLayout(new GridLayout(2, 3, 4, 4));
            }
            Designhelper designhelper = new Designhelper();
            designhelper.DesignPage(jpnNext, sql.select());
            list = designhelper.LimitPage(sql.select(), start, end);
            designhelper.DesignSanPham(jpnDSsanpham, testSQL.select());

        } catch (Exception e) {
            System.out.println(e);
        }

    }

    public String AutogetMaHD() {
        HoaDonDAO hdDao = new HoaDonDAO();
        String chuoi = "";
        List<HoaDon> list = hdDao.selectAll();
        if (list.isEmpty()) {
            chuoi = "HD001";
            lblbuton_thanhToan.setToolTipText(chuoi);
            return lblbuton_thanhToan.getToolTipText();
        } else {
            int index = list.size() - 1;
            int so = Integer.parseInt(list.get(index).getMaHoaDon().substring(2)) + 1;
            switch (String.valueOf(so).length()) {
                case 1:
                    chuoi = "HD00" + so;
                    break;
                case 2:
                    chuoi = "HD0" + so;
                    break;
                case 3:
                    chuoi = "HD" + so;
                    break;
            }
            lblbuton_thanhToan.setToolTipText(chuoi);
            return lblbuton_thanhToan.getToolTipText();
        }
    }

    public void getTongTien() {
        double tongtien = 0;
        for (int i = 0; i < DongCTHD.size(); i++) {
            tongtien += (DongCTHD.get(i).getMaHoaDon().getTongTien());
        }
        double ChietKhau;
        if (txtChietKhau.getText().trim().equals("")) {
            ChietKhau = 0;
            lblThanhTien.setText(String.valueOf(chuyentien.format(tongtien * (100 - ChietKhau) / 100)) + " VNĐ");
            lblThanhTien.setName(String.valueOf(tongtien * (100 - ChietKhau) / 100));
            lblThanhTien.setToolTipText(String.valueOf(tongtien * (100 - ChietKhau) / 100));
        } else {
            ChietKhau = Double.parseDouble(txtChietKhau.getText());
            lblThanhTien.setText(String.valueOf(chuyentien.format(tongtien * (100 - ChietKhau) / 100)) + " VNĐ");
            lblThanhTien.setName(String.valueOf(tongtien * (100 - ChietKhau) / 100));
            lblThanhTien.setToolTipText(String.valueOf(tongtien * (100 - ChietKhau) / 100));
        }

    }

    public void GetHD() {
        java.sql.Timestamp date = new java.sql.Timestamp(System.currentTimeMillis());
        HoaDon hoadon = new HoaDon();
        KhachHang kh = new KhachHang();
        NguoiDung nd = new NguoiDung();
        hoadon.setMaHoaDon(lblbuton_thanhToan.getToolTipText());
        nd.setMaNguoidung(lblUsers.getName());
        double ChietKhau = Double.parseDouble(txtChietKhau.getText());
        hoadon.setChietKhau(ChietKhau);
        hoadon.setTongTien(Double.parseDouble(lblThanhTien.getToolTipText()));
        System.out.println(lblThanhTien.getToolTipText());
        kh.setMakh(lbltenKH.getName());
        hoadon.setMaKhachHang(kh);
        hoadon.setTrangThai(true);
        hoadon.setMaNguoiDung(nd);
        hoadon.setNgayHD(date);
        hd.add(hoadon);

    }

    public void DongGoiHD() {
        HoaDon hoadon = new HoaDon();
        for (int i = 0; i < hd.size(); i++) {
            hoadon.setMaHoaDon(hd.get(i).getMaHoaDon());
            hoadon.setChietKhau(hd.get(i).getChietKhau());
            hoadon.setMaNguoiDung(hd.get(i).getMaNguoiDung());
            hoadon.setMaKhachHang(hd.get(i).getMaKhachHang());
            hoadon.setTrangThai(hd.get(i).isTrangThai());
            hoadon.setTongTien(hd.get(i).getTongTien());
            hoadon.setNgayHD(hd.get(i).getNgayHD());

        }
        SavehoaDon.add(hoadon);
    }

    public void diemtichluy() {
        double tongtien = 0;
        lbldiemtichluy.setText("0");
        if (lbldiemtichluy.getName().equals("true")) {
            for (int i = 0; i < DongCTHD.size(); i++) {
                tongtien += (DongCTHD.get(i).getMaHoaDon().getTongTien());
                if (lblThanhTien.getText().equals("0 VNĐ")) {
                    lbldiemtichluy.setText("0");
                } else if (tongtien >= 30000 && tongtien < 50000 && !lbltenKH.getName().equals("KH000")) {
                    lbldiemtichluy.setText("35");
                } else if (tongtien >= 50000 && tongtien < 100000 && !lbltenKH.getName().equals("KH000")) {
                    lbldiemtichluy.setText("55");
                } else if (tongtien >= 100000 && tongtien < 200000 && !lbltenKH.getName().equals("KH000")) {
                    lbldiemtichluy.setText("105");
                } else if (tongtien >= 250000 && tongtien < 350000 && !lbltenKH.getName().equals("KH000")) {
                    lbldiemtichluy.setText("205");
                } else if (tongtien >= 400000 && tongtien < 500000 && !lbltenKH.getName().equals("KH000")) {
                    lbldiemtichluy.setText("335");
                } else if (tongtien >= 550000 && tongtien < 1000000 && !lbltenKH.getName().equals("KH000")) {
                    lbldiemtichluy.setText("555");
                } else if (tongtien >= 1100000 && tongtien < 1500000 && !lbltenKH.getName().equals("KH000")) {
                    lbldiemtichluy.setText("805");
                } else if (tongtien >= 1100000 && tongtien < 2500000 && !lbltenKH.getName().equals("KH000")) {
                    lbldiemtichluy.setText("1005");
                } else if (tongtien >= 2550000 && tongtien < 5050000 && !lbltenKH.getName().equals("KH000")) {
                    lbldiemtichluy.setText("1500");
                } else if (tongtien >= 5550000 && !lbltenKH.getName().equals("KH000")) {
                    lbldiemtichluy.setText("1700");

                }
            }
        }

    }

    public void updateDiem() {
        int diemTichLuy = 0;
        diemTichLuy += Integer.parseInt(txtdiem.getText()) + Integer.parseInt(lbldiemtichluy.getText());
        String thanhdiem = String.valueOf(diemTichLuy);
        int gioiHan = Integer.parseInt(txtdiem.getText());
        if (gioiHan >= 5000) {
            txtdiem.setForeground(Color.red);
        } else {
            JDBCHelper.executeUpdate(" UPDATE dbo.KhachHang SET diemThuong = ' " + thanhdiem + "' where makh ='" + lbltenKH.getName() + "'");
        }

    }

    public void InsertHD() {
        try {
            HoaDon hd = new HoaDon();
            for (int i = 0; i < SavehoaDon.size(); i++) {
                HoaDonDAO in = new HoaDonDAO();
                hd.setMaHoaDon(SavehoaDon.get(i).getMaHoaDon());
                hd.setMaKhachHang(SavehoaDon.get(i).getMaKhachHang());
                hd.setMaNguoiDung(SavehoaDon.get(i).getMaNguoiDung());
                hd.setChietKhau(SavehoaDon.get(i).getChietKhau());
                hd.setTongTien(SavehoaDon.get(i).getTongTien());
                hd.setTrangThai(SavehoaDon.get(i).isTrangThai());
                hd.setNgayHD(SavehoaDon.get(i).getNgayHD());
                in.insert(hd);

            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    public void InsertHDCT() {
        try {

            CTHoaDon cthd = new CTHoaDon();
            for (int i = 0; i < DongCTHD.size(); i++) {
                CTHoaDonDAO insert = new CTHoaDonDAO();
                cthd.setMaHoaDon(DongCTHD.get(i).getMaHoaDon());
                cthd.setMaSanPham(DongCTHD.get(i).getMaSanPham());
                cthd.setSoLuong(DongCTHD.get(i).getSoLuong());
                cthd.setSizeSP(DongCTHD.get(i).getSizeSP());
                cthd.setExtra(DongCTHD.get(i).getExtra());
                insert.insert(cthd);
                System.out.println(DongCTHD.get(i).getMaSanPham().getMaSanPham());

            }
        } catch (Exception e) {
            System.out.println("Not: " + e);
        }
    }

    public void Reset() {
        jpldonhang.removeAll();
        DongCTHD.removeAll(DongCTHD);
        SavehoaDon.removeAll(SavehoaDon);
        lblTamTinh.setText("0 VNĐ");
        lblThanhTien.setText("0 VNĐ");
        lblThanhTien.setToolTipText("0");
        lbltenKH.setText(" x Khách lẻ");
        lbltenKH.setName("KH000");
        txtChietKhau.setText("0");
        txttienkhach.setText("");
        lbltienthua.setText("0");
        lbldiemtichluy.setText("0");
        txtdiem.hide();
        lbldiem.hide();
    }

    public void CountSoLuongHoaDonTrenWeb() {

        Timehelper time = new Timehelper();
        lblsound.setName("sound");
        time.DatLichTimer(lblorderweb, lblsound, "EXEC dbo.SoLuongDatMuaTrenWeb");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JPanel Card;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jSDonHang;
    private javax.swing.JScrollPane jSSanPham;
    protected static javax.swing.JPanel jfBangHang;
    private javax.swing.JPanel jplDonHang;
    private javax.swing.JPanel jplHoaDon;
    protected static javax.swing.JPanel jpldonhang;
    private javax.swing.JPanel jpnDSsanpham;
    private javax.swing.JPanel jpnDangXuatBanHang;
    private javax.swing.JPanel jpnNext;
    private javax.swing.JPanel jpnQuayVeBanHang;
    private javax.swing.JPanel jpnShowMenuOut;
    private javax.swing.JPanel jpnTenDangNhapBanHang;
    private javax.swing.JPanel jpnToolbar19;
    private javax.swing.JLabel lblAn_BanHang;
    private javax.swing.JLabel lblDangXuatBangHang;
    private javax.swing.JLabel lblOutBangHang;
    private javax.swing.JLabel lblQuayVeBangHang;
    private javax.swing.JLabel lblShoworderweb;
    protected static javax.swing.JLabel lblTamTinh;
    protected static javax.swing.JLabel lblThanhTien;
    protected static javax.swing.JLabel lblThongBao;
    private javax.swing.JLabel lblUsers;
    private javax.swing.JLabel lblVienTxt;
    private javax.swing.JLabel lblbanhmi;
    private javax.swing.JLabel lblbanhngot;
    protected static javax.swing.JLabel lblbuton_thanhToan;
    private javax.swing.JLabel lblcoffe;
    private javax.swing.JLabel lbldiem;
    private javax.swing.JLabel lbldiemtichluy;
    private javax.swing.JLabel lblfee;
    private javax.swing.JLabel lblorderweb;
    private javax.swing.JLabel lblsound;
    private javax.swing.JLabel lbltea;
    protected static javax.swing.JLabel lbltenKH;
    private javax.swing.JLabel lbltenTienthua;
    private javax.swing.JLabel lbltienthua;
    private javax.swing.JLabel lbltimSDT;
    protected static javax.swing.JTextField txtChietKhau;
    private javax.swing.JTextField txtTimKiem;
    protected static javax.swing.JTextField txtTimSDT;
    private javax.swing.JTextField txtdiem;
    private javax.swing.JTextField txttienkhach;
    // End of variables declaration//GEN-END:variables
}

//Code//

