/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhom3.qlcf.view.form.nhacungcap;

import com.nhom3.qlcf.dao.KhachHangDAO;
import com.nhom3.qlcf.dao.NhaCungCapDAO;
import com.nhom3.qlcf.model.KhachHang;
import com.nhom3.qlcf.model.NhaCungCap;
import com.nhom3.qlcf.view.form.hanghoa.*;
import java.awt.Color;
import java.util.List;
import javax.print.attribute.standard.MediaSize;

/**
 *
 * @author baotri1998
 */
public class Themnhacungcap extends javax.swing.JPanel {

    /**
     * Creates new form SuaHangHoa
     */
    NhaCungCapDAO dao = new NhaCungCapDAO();

    public Themnhacungcap() {
        initComponents();
        txtmanhacungcap.setText(AutogetNCC());
    }

    public String AutogetNCC() {
        NhaCungCapDAO dao = new NhaCungCapDAO();
        String chuoi = "";
        List<NhaCungCap> list = dao.selectAll();
        if (list.isEmpty()) {
            chuoi = "NCC001";
            return chuoi;
        } else {
            int index = list.size() - 1;
            int so = Integer.parseInt(list.get(index).getMaNhaCungCap().substring(3)) + 1;
            switch (String.valueOf(so).length()) {
                case 1:
                    chuoi = "NCC00" + so;
                    break;
                case 2:
                    chuoi = "NCC0" + so;
                    break;
                case 3:
                    chuoi = "NCC" + so;
                    break;
            }

            return chuoi;
        }
    }

    public boolean Check() {
        if (txtTendoitac.getText().trim().equals("")) {
            lbltb.setText("Tên đối tác là bắt buột");
            lbltb.setForeground(Color.red);
            return false;
        } if (txtTendoitac.getText().length()<6) {
            lbltb.setText("Tên đối tác phải ít nhất 6 kí tự");
            lbltb.setForeground(Color.red);
            return false;
        } else if (txtDienThoai.getText().trim().equals("")) {
            lbltb.setText("SDT đối tác là bắt buột");
            lbltb.setForeground(Color.red);
            return false;
        } else if (!txtDienThoai.getText().matches("[0-9]+")) {
            lbltb.setText("SDT phải là số");
            lbltb.setForeground(Color.red);
            return false;
        } else if (txtDienThoai.getText().length() < 10 || txtDienThoai.getText().length() > 13) {
            lbltb.setText("SDT phải là [10-13] số");
            lbltb.setForeground(Color.red);
            return false;
        } else if (dao.checkMa(txtDienThoai.getText())) {
            lbltb.setText("SDT này đã có rồi");
            lbltb.setForeground(Color.red);
            return false;
        } else if (txtdiachi.getText().trim().equals("")) {
            lbltb.setText("Địa chỉ đối tác là bắt buột");
            lbltb.setForeground(Color.red);
            return false;
        }
        return true;
    }

    public void insert() {
        NhaCungCapDAO dao = new NhaCungCapDAO();
        NhaCungCap ncc = new NhaCungCap();
        ncc.setMaNhaCungCap(txtmanhacungcap.getText());
        ncc.setTenNhaCC(txtTendoitac.getText());
        ncc.setDienThoai(txtDienThoai.getText());
        ncc.setDiaChi(txtdiachi.getText());
        if (cobTrangThai.getSelectedIndex() == 0) {
            ncc.setTrangThai(true);
        } else {
            ncc.setTrangThai(false);
        }
        dao.insert(ncc);
        lbltb.setText("Thêm thành công!");
        lbltb.setForeground(Color.green);
        txtdiachi.setText("");
        txtDienThoai.setText("");
        txtTendoitac.setText("");
        txtmanhacungcap.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtmanhacungcap = new javax.swing.JTextField();
        lblvien = new javax.swing.JLabel();
        lblvien1 = new javax.swing.JLabel();
        txtTendoitac = new javax.swing.JTextField();
        lblpass = new javax.swing.JLabel();
        lbluser = new javax.swing.JLabel();
        lblpass1 = new javax.swing.JLabel();
        lblvien2 = new javax.swing.JLabel();
        lblpass3 = new javax.swing.JLabel();
        txtdiachi = new javax.swing.JTextField();
        txtDienThoai = new javax.swing.JTextField();
        lblpass2 = new javax.swing.JLabel();
        lblvien3 = new javax.swing.JLabel();
        cobTrangThai = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        lbltb = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN CẦN NHẬP");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel1.setMaximumSize(new java.awt.Dimension(122, 17));
        jLabel1.setMinimumSize(new java.awt.Dimension(122, 17));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(122, 17));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 50));

        txtmanhacungcap.setEditable(false);
        txtmanhacungcap.setBorder(null);
        txtmanhacungcap.setOpaque(false);
        txtmanhacungcap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmanhacungcapActionPerformed(evt);
            }
        });
        jPanel1.add(txtmanhacungcap, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 102, 260, 40));

        lblvien.setForeground(new java.awt.Color(255, 0, 0));
        lblvien.setText("___________________________________________");
        jPanel1.add(lblvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 114, 260, 30));

        lblvien1.setText("___________________________________________");
        jPanel1.add(lblvien1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 260, 30));

        txtTendoitac.setBackground(new java.awt.Color(255, 204, 0));
        txtTendoitac.setBorder(null);
        txtTendoitac.setOpaque(false);
        txtTendoitac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTendoitacActionPerformed(evt);
            }
        });
        jPanel1.add(txtTendoitac, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 259, 40));

        lblpass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblpass.setText("Tên Đối Tác*:");
        jPanel1.add(lblpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 90, 20));

        lbluser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbluser.setText("Mã Nhà Cung Cấp*:");
        jPanel1.add(lbluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 84, 140, 20));

        lblpass1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblpass1.setText("Số Điện Thoại*:");
        jPanel1.add(lblpass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 100, 20));

        lblvien2.setText("___________________________________________");
        jPanel1.add(lblvien2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 260, 30));

        lblpass3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblpass3.setText("Địa Chỉ:");
        jPanel1.add(lblpass3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 100, 20));

        txtdiachi.setBorder(null);
        txtdiachi.setOpaque(false);
        jPanel1.add(txtdiachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 259, 40));

        txtDienThoai.setBackground(new java.awt.Color(255, 204, 0));
        txtDienThoai.setBorder(null);
        txtDienThoai.setOpaque(false);
        txtDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDienThoaiActionPerformed(evt);
            }
        });
        jPanel1.add(txtDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 260, 40));

        lblpass2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblpass2.setText("Trạng Thái:");
        jPanel1.add(lblpass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 80, 20));

        lblvien3.setText("___________________________________________");
        jPanel1.add(lblvien3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 260, 30));

        cobTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hợp Tác", "Chưa Hợp Tác" }));
        jPanel1.add(cobTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 210, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Thêm");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 140, 40));

        lbltb.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbltb.setForeground(new java.awt.Color(255, 0, 0));
        lbltb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltb.setText(".");
        jPanel1.add(lbltb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 380, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDienThoaiActionPerformed

    private void txtmanhacungcapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmanhacungcapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmanhacungcapActionPerformed

    private void txtTendoitacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTendoitacActionPerformed
        // TODO add your hantxtdiachihere:
    }//GEN-LAST:event_txtTendoitacActionPerformed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        // TODO add your handling code here:
        if (Check()) {
            insert();
        }
    }//GEN-LAST:event_jLabel4MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cobTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblpass;
    private javax.swing.JLabel lblpass1;
    private javax.swing.JLabel lblpass2;
    private javax.swing.JLabel lblpass3;
    private javax.swing.JLabel lbltb;
    private javax.swing.JLabel lbluser;
    private javax.swing.JLabel lblvien;
    private javax.swing.JLabel lblvien1;
    private javax.swing.JLabel lblvien2;
    private javax.swing.JLabel lblvien3;
    private javax.swing.JTextField txtDienThoai;
    private javax.swing.JTextField txtTendoitac;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtmanhacungcap;
    // End of variables declaration//GEN-END:variables
}
