/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhom3.qlcf.view.form.doanhthu;

import com.nhom3.qlcf.helper.JDBCHelper;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author baotri1998
 */
public class LichSuBanHang extends javax.swing.JPanel {
    
    DefaultTableModel model = null;
    double tongDoanhThu = 0;

    /**
     * Creates new form LichSuMuaHang
     */
    public LichSuBanHang() {
        initComponents();
        tblLishSuMuaHang.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
        tblLishSuMuaHang.setFont(new Font("Tohoma", Font.PLAIN, 12));
        tblLishSuMuaHang.getTableHeader().setOpaque(false);
        tblLishSuMuaHang.getTableHeader().setBackground(new Color(0, 0, 0));
        tblLishSuMuaHang.getTableHeader().setForeground(new Color(255, 255, 255));
        tblLishSuMuaHang.setRowHeight(22);
        fillToTable();
        
        for (int i = 0; i < tblLishSuMuaHang.getRowCount(); i++) {
            double tien = (double) tblLishSuMuaHang.getValueAt(i, 4);
            tongDoanhThu += tien;
        }
        lblDoanhThu.setText("Tổng doanh thu: " + new DecimalFormat("#,###,###").format(tongDoanhThu));        
    } 
    
    private void showDetails() {
        int index = tblLishSuMuaHang.getSelectedRow();
        lblNgayTao.setText("Ngày tạo: " + String.valueOf(tblLishSuMuaHang.getValueAt(index, 3)));
//        lblSoLuong.setText("Tổng số lượng: " + String.valueOf(tblLishSuMuaHang.getValueAt(index, 2)));
    }
    
    private void fillToTable() {
        try {
            ResultSet rs = JDBCHelper.executeQuery("SELECT * FROM dbo.LichSuBanHang");
            model = (DefaultTableModel) tblLishSuMuaHang.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                Object[] row = new Object[]{rs.getString(1), rs.getDouble(2), rs.getInt(3), rs.getDate(4), rs.getDouble(5)};
                model.addRow(row);
            }
        } catch (SQLException ex) {
            throw new RuntimeException(ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLishSuMuaHang = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        lblNgayTao = new javax.swing.JLabel();
        lblDoanhThu = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tblLishSuMuaHang.setForeground(new java.awt.Color(51, 51, 51));
        tblLishSuMuaHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên SP", "Giá Bán", "Số Lượng", "Ngày hóa đơn", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLishSuMuaHang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblLishSuMuaHang.setFocusable(false);
        tblLishSuMuaHang.setGridColor(new java.awt.Color(0, 0, 0));
        tblLishSuMuaHang.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblLishSuMuaHang.setRowHeight(25);
        tblLishSuMuaHang.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblLishSuMuaHang.setShowHorizontalLines(false);
        tblLishSuMuaHang.setShowVerticalLines(false);
        tblLishSuMuaHang.setSurrendersFocusOnKeystroke(true);
        tblLishSuMuaHang.getTableHeader().setReorderingAllowed(false);
        tblLishSuMuaHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblLishSuMuaHangMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tblLishSuMuaHang);
        if (tblLishSuMuaHang.getColumnModel().getColumnCount() > 0) {
            tblLishSuMuaHang.getColumnModel().getColumn(0).setResizable(false);
            tblLishSuMuaHang.getColumnModel().getColumn(1).setResizable(false);
            tblLishSuMuaHang.getColumnModel().getColumn(2).setResizable(false);
            tblLishSuMuaHang.getColumnModel().getColumn(3).setResizable(false);
            tblLishSuMuaHang.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("LỊCH SỬ BÁN HÀNG");

        lblNgayTao.setText("Ngày tạo: ");

        lblDoanhThu.setText("Tổng doanh thu:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(lblDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoanhThu)
                    .addComponent(lblNgayTao))
                .addGap(13, 13, 13)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void tblLishSuMuaHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLishSuMuaHangMousePressed
        // TODO add your handling code here:
        showDetails();
    }//GEN-LAST:event_tblLishSuMuaHangMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDoanhThu;
    private javax.swing.JLabel lblNgayTao;
    private javax.swing.JTable tblLishSuMuaHang;
    // End of variables declaration//GEN-END:variables
}
