/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhom3.qlcf.view.form.doanhthu;

import com.nhom3.qlcf.helper.JDBCHelper;
import java.awt.Color;
import java.awt.Font;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author baotri1998
 */
public class TongSPCoDoanhThuCao extends javax.swing.JPanel {

    /**
     * Creates new form LichSuMuaHang
     */
    public TongSPCoDoanhThuCao() {
        initComponents();
        tblDoanhThuTheoSP.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
        tblDoanhThuTheoSP.setFont(new Font("Tohoma", Font.PLAIN, 12));
        tblDoanhThuTheoSP.getTableHeader().setOpaque(false);
        tblDoanhThuTheoSP.getTableHeader().setBackground(new Color(0, 0, 0));
        tblDoanhThuTheoSP.getTableHeader().setForeground(new Color(255, 255, 255));
        tblDoanhThuTheoSP.setRowHeight(22);
        fillToTable();

    }

    private void fillToTable() {
        ResultSet rs = JDBCHelper.executeQuery("EXEC dbo.DoanhThuTheoSP");
        DefaultTableModel model = (DefaultTableModel) tblDoanhThuTheoSP.getModel();
        model.setRowCount(0);
        try {
            while (rs.next()) {
                Object[] row = new Object[]{rs.getString(1), rs.getString(2), rs.getDouble(3), rs.getInt(4), rs.getDouble(5)};
                model.addRow(row);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDoanhThuTheoSP = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tblDoanhThuTheoSP.setForeground(new java.awt.Color(51, 51, 51));
        tblDoanhThuTheoSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "maSP", "Tên SP", "Giá Bán", "Số Lượng", "Tổng Tiền"
            }
        ));
        tblDoanhThuTheoSP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblDoanhThuTheoSP.setFocusable(false);
        tblDoanhThuTheoSP.setGridColor(new java.awt.Color(0, 0, 0));
        tblDoanhThuTheoSP.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblDoanhThuTheoSP.setRowHeight(25);
        tblDoanhThuTheoSP.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblDoanhThuTheoSP.setShowHorizontalLines(false);
        tblDoanhThuTheoSP.setShowVerticalLines(false);
        tblDoanhThuTheoSP.setSurrendersFocusOnKeystroke(true);
        tblDoanhThuTheoSP.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tblDoanhThuTheoSP);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("SẢN PHẨM  DOANH THU CAO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblDoanhThuTheoSP;
    // End of variables declaration//GEN-END:variables
}
